[:abort_check_catch, :abort_reset, :abort_safe_execute, :abort_signal,
 :agent_abort, :agent_chat, :agent_chat_continue, :agent_chat_live,
 :agent_chat_with_orphan, :agent_stream, :application_not_started,
 :application_started, :assert_abort_caught, :assert_abort_flag,
 :assert_abort_reason, :assert_abort_reset, :assert_aborted,
 :assert_active_tool_contains, :assert_active_tool_count, :assert_agent_reply,
 :assert_anchor_count, :assert_api_key_result,
 :assert_application_already_started, :assert_auth_lock_recovered,
 :assert_auth_method, :assert_auth_token, :assert_authorize_url,
 :assert_auto_compacted, :assert_auto_no_action, :assert_backend_error,
 :assert_backend_reply, :assert_branch_summary,
 :assert_branch_summary_preserved, :assert_capability_match,
 :assert_command_count, :assert_command_error, :assert_command_exists,
 :assert_command_result, :assert_common_ancestor, :assert_compacted,
 :assert_compaction_error, :assert_compaction_not_triggered,
 :assert_compaction_triggered, :assert_compat_detected,
 :assert_config_blocks_all, :assert_config_no_filter,
 :assert_conflicting_extension_removed, :assert_content_indices_sequential,
 :assert_content_is_text, :assert_context_compactable,
 :assert_context_window_size, :assert_conversation_contains,
 :assert_converted_has_tool_calls, :assert_converted_messages,
 :assert_converted_tool_call_id, :assert_converted_tool_name,
 :assert_cost_history, :assert_cost_includes_partial, :assert_cost_summary,
 :assert_current_model, :assert_current_provider, :assert_db_exists,
 :assert_dir_exists, :assert_empty_content_filtered, :assert_entry_count,
 :assert_entry_has_metadata, :assert_entry_order, :assert_env_unchanged,
 :assert_error_messages_filtered, :assert_ets_table_exists, :assert_exit_code,
 :assert_extension_cleanup_called, :assert_extension_commands,
 :assert_extension_conflict_error, :assert_extension_count,
 :assert_extension_error, :assert_extension_loaded, :assert_extension_tools,
 :assert_fields_stripped, :assert_file_content, :assert_file_exists,
 :assert_file_has_bom, :assert_file_has_crlf, :assert_file_no_crlf,
 :assert_file_ops_contains, :assert_file_ops_text, :assert_flush_reset,
 :assert_follow_up_empty, :assert_follow_up_message, :assert_fork_cleaned,
 :assert_formatted_length, :assert_handler_error_propagated,
 :assert_handoff_summary_max_lines, :assert_handoff_summary_not_empty,
 :assert_hook_blocked, :assert_hook_error_logged, :assert_hook_fired,
 :assert_import_resolved, :assert_initial_state_persisted,
 :assert_is_tool_result, :assert_jsonl_contains, :assert_jsonl_not_contains,
 :assert_last_call, :assert_last_call_nil, :assert_last_error,
 :assert_lock_race_result, :assert_lookup_api_key_env, :assert_lookup_error,
 :assert_lookup_ok, :assert_max_tokens_ge_budget, :assert_model_count,
 :assert_model_error, :assert_model_list_count,
 :assert_model_references_cleaned, :assert_model_string,
 :assert_no_compaction_error, :assert_no_compaction_on_new_model,
 :assert_no_crash, :assert_no_extensions_loaded, :assert_no_hook_error,
 :assert_no_loop_crash, :assert_no_orphan_process, :assert_no_race_condition,
 :assert_no_registry_processes, :assert_no_retry, :assert_no_session_processes,
 :assert_normalized_path, :assert_normalized_path_contains,
 :assert_normalized_path_is_absolute, :assert_not_compacted,
 :assert_observer_saw_updated_state, :assert_original_messages_intact,
 :assert_other_children_unchanged, :assert_output_contains,
 :assert_output_not_contains, :assert_partial_content,
 :assert_partial_json_empty, :assert_partial_json_field,
 :assert_partial_json_has_key, :assert_partial_json_ok,
 :assert_partial_tokens_preserved, :assert_pending_cleared,
 :assert_preset_contains, :assert_preset_count, :assert_preset_not_contains,
 :assert_previous_summary, :assert_previous_summary_nil,
 :assert_prompt_contains, :assert_prompt_contains_context,
 :assert_prompt_contains_cwd, :assert_prompt_contains_time, :assert_prompt_mode,
 :assert_prompt_text, :assert_provider_count, :assert_provider_current_nil,
 :assert_provider_error, :assert_provider_list_order,
 :assert_provider_registered, :assert_provider_retries_enabled,
 :assert_provider_timeout, :assert_query_results, :assert_read_image,
 :assert_read_text, :assert_registry_error, :assert_registry_running,
 :assert_rendered_content, :assert_required_fields_added,
 :assert_resource_content, :assert_resource_count,
 :assert_result_content_contains, :assert_result_content_not_contains,
 :assert_result_field, :assert_retry_happened, :assert_rpc_error,
 :assert_rpc_parsed, :assert_rpc_response_json, :assert_rpc_result,
 :assert_safe_execute_result, :assert_search_result_count,
 :assert_search_results, :assert_sequence_invalid, :assert_sequence_valid,
 :assert_session_backend_resolved, :assert_session_error,
 :assert_session_header_preserved, :assert_session_reply,
 :assert_session_restarted, :assert_setting_nil, :assert_setting_value,
 :assert_settings_list, :assert_start_failed, :assert_steering_empty,
 :assert_steering_message, :assert_steering_message_nil,
 :assert_steering_not_pending, :assert_steering_pending,
 :assert_steering_skip_contains, :assert_stream_callback_events,
 :assert_stream_callback_events_empty, :assert_stream_callback_events_include,
 :assert_stream_content, :assert_stream_events, :assert_summary_exists,
 :assert_summary_has_tool_calls, :assert_summary_nil,
 :assert_supervisor_running, :assert_system_preserved, :assert_tape_branches,
 :assert_tape_context_path, :assert_tape_error,
 :assert_tape_has_compaction_anchor, :assert_tape_last_content,
 :assert_telemetry_received, :assert_telemetry_sequence, :assert_template_error,
 :assert_template_exists, :assert_template_list_count,
 :assert_template_variables, :assert_thinking_budget,
 :assert_thinking_config_flat, :assert_thinking_invalid,
 :assert_thinking_params, :assert_thinking_params_empty, :assert_thinking_valid,
 :assert_token_estimate, :assert_token_expired, :assert_token_refreshed,
 :assert_tool_config_error, :assert_tool_error,
 :assert_tool_error_has_available_tools, :assert_tool_event_name,
 :assert_tool_event_sequence, :assert_tool_not_called,
 :assert_tool_pairs_intact, :assert_tool_result_buffered,
 :assert_tool_result_content, :assert_tool_result_details_nil,
 :assert_tool_result_details_value, :assert_tool_result_has_details,
 :assert_tool_result_is_error, :assert_tool_result_not_error,
 :assert_tool_schema_has_field, :assert_tool_success, :assert_tool_truncated,
 :assert_tool_was_called, :assert_truncation_notification,
 :assert_truncation_result, :attach_stream_callback, :attach_telemetry_handler,
 :auth_logout, :auto_compact, :buffer_tool_result_during_stream,
 :build_default_prompt, :build_handoff_summary, :build_summarize_prompt,
 :build_system_prompt, :build_thinking_config, :build_workspace_prompt,
 :check_e2e_provider, :check_model_capability, :check_provider_compat,
 :check_token_expired, :cleanup_extension, :cleanup_model_registry,
 :cleanup_provider_registry, :cleanup_settings, :clear_file,
 :clear_stream_callback, :compact_with_tool_calls, :compaction_lock_acquired,
 :compaction_messages, :compaction_messages_with_branch_summary,
 :compaction_messages_with_session_header, :compaction_messages_with_summary,
 :compaction_messages_with_system, :compaction_messages_with_tool_calls,
 :compaction_messages_with_tools, :compaction_summarize_fn_fail,
 :compaction_summarize_fn_ok, :compaction_summarize_fn_raise,
 :concurrent_lock_acquire, :configure_agent, :configure_hooks,
 :convert_messages, :corrupt_auth_lock_file, :corrupt_jsonl,
 :create_auth_lock_file, :create_binary_file, :create_bom_file,
 :create_conflicting_extensions, :create_expiring_token, :create_extension_dir,
 :create_extension_file, :create_extension_with_import, :create_large_file,
 :create_png_file, :create_resource_dir, :create_resource_file,
 :create_session_via_supervisor, :create_settings_file, :create_symlink,
 :create_temp_dir, :create_temp_file, :cross_provider_messages,
 :cross_provider_messages_with_custom_role, :cross_provider_messages_with_error,
 :cross_provider_messages_with_gateway,
 :cross_provider_messages_with_string_keys,
 :cross_provider_messages_with_thinking,
 :cross_provider_messages_with_unsupported_fields,
 :cross_provider_multipart_message, :cross_provider_tool_calls_message,
 :cross_provider_tool_calls_with_id, :cross_provider_tool_calls_with_name,
 :delete_file, :detect_auth_method, :discover_extensions,
 :discover_extensions_with_flag, :emit_content_blocks, :emit_event,
 :emit_event_with_message, :exchange_auth_code, :execute_command,
 :execute_command_expect_error, :execute_hook_during_stream,
 :extract_file_operations, :extract_prompt_file_ops,
 :find_deepest_common_ancestor, :find_previous_summary, :format_conversation,
 :generate_authorize_url, :generate_branch_summary, :generate_content,
 :get_active_tools, :get_api_key, :get_api_key_via_auth, :get_model_string,
 :get_model_string_safe, :get_preset, :get_provider_retry_config, :get_setting,
 :get_setting_safe, :get_template, :get_template_expect_error,
 :get_thinking_budget, :get_tool_schema, :init_command_registry,
 :init_cost_tracker, :init_model_registry, :init_model_registry_when,
 :init_prompt_template, :init_prompt_templates, :init_provider_registry,
 :init_session, :init_session_expect_error, :init_settings, :init_tool_config,
 :inject_follow_up, :inject_steering, :kill_session_process, :list_models,
 :list_settings, :load_all_extensions, :load_extension,
 :load_extension_with_imports, :load_resources,
 :load_resources_from_duplicate_paths, :load_resources_from_paths,
 :lookup_model_by_string, :mock_llm_response, :mock_orphan_tool_result,
 :mock_registry_start_failure, :mock_reqllm_response, :mock_stream_response,
 :mutate_last_setting_value, :normalize_path, :parse_rpc_request,
 :partial_json_accumulate, :partial_json_parse, :prompt_messages_multi_tools,
 :prompt_messages_plain, :prompt_messages_with_long_content,
 :prompt_messages_with_summary, :provider_fallback,
 :provider_fallback_expect_error, :push_steering_message, :record_llm_call,
 :record_partial_llm_call, :refresh_auth_token, :register_command,
 :register_failing_event_handler, :register_hook, :register_model,
 :register_model_with_context_window, :register_model_with_defaults,
 :register_mutating_hook, :register_provider,
 :register_provider_with_invalid_config, :register_provider_with_timeout,
 :register_state_observer_hook, :register_template, :reload_resources,
 :reload_settings, :render_template, :reset_cost_tracker, :rpc_dispatch,
 :rpc_dispatch_missing, :rpc_dispatch_raise, :rpc_dispatch_with_attachments,
 :rpc_handle, :run_as_backend, :send_abort_signal, :session_prompt,
 :set_active_tools, :set_active_tools_safe, :set_config_empty_array,
 :set_env_api_key, :set_file_permission, :set_no_extensions_flag, :set_setting,
 :set_var, :setup_abort_scenario, :simulate_token_check, :start_application,
 :start_application_catch, :start_mock_stream, :steering_check,
 :steering_check_follow_up, :steering_check_steering, :steering_push,
 :steering_push_typed, :steering_queue_empty, :steering_skip_result,
 :stop_application, :stream_tool_chunks, :switch_model,
 :switch_model_after_overflow, :switch_provider, :switch_provider_expect_error,
 :tape_add_pending, :tape_append, :tape_branch_from, :tape_build_context,
 :tape_close_db, :tape_fork, :tape_handoff, :tape_init, :tape_navigate,
 :tape_persist_initial_state, :tape_restore_parent, :tape_switch_session,
 :thinking_to_provider, :tool_bash, :tool_bash_with_abort,
 :tool_dispatch_nil_params, :tool_edit, :tool_edit_diff, :tool_find, :tool_grep,
 :tool_ls, :tool_read, :tool_result_error, :tool_result_from_text,
 :tool_result_new, :tool_truncate, :tool_write, :trigger_compaction,
 :trigger_overflow_on_model, :truncate_head, :truncate_line, :truncate_tail,
 :try_register_duplicate_registry, :validate_model, :validate_stream_events,
 :validate_thinking_level, :validate_tools, :when_acquire_lock, :when_compact,
 :when_compact_and_handoff, :when_estimate_tokens, :when_release_lock,
 :when_tape_append, :when_tape_between_anchors, :when_tape_flush,
 :when_tape_fork, :when_tape_get_last_assistant, :when_tape_handoff,
 :when_tape_init, :when_tape_merge, :when_tape_rebuild_index, :when_tape_search]