[:abort_check_catch, :abort_reset, :abort_safe_execute, :abort_signal,
 :agent_abort, :agent_chat, :agent_chat_continue, :agent_chat_live,
 :agent_stream, :assert_abort_caught, :assert_abort_flag, :assert_abort_reason,
 :assert_abort_reset, :assert_aborted, :assert_agent_reply,
 :assert_anchor_count, :assert_api_key_result, :assert_auth_method,
 :assert_auth_token, :assert_authorize_url, :assert_auto_compacted,
 :assert_auto_no_action, :assert_branch_summary, :assert_command_count,
 :assert_command_error, :assert_command_exists, :assert_command_result,
 :assert_compacted, :assert_compaction_error, :assert_compaction_not_triggered,
 :assert_compaction_triggered, :assert_content_is_text,
 :assert_context_compactable, :assert_conversation_contains,
 :assert_converted_has_tool_calls, :assert_converted_messages,
 :assert_cost_history, :assert_cost_summary, :assert_current_model,
 :assert_current_provider, :assert_db_exists, :assert_delay_ms,
 :assert_dir_exists, :assert_entry_count, :assert_entry_has_metadata,
 :assert_error_class, :assert_exit_code, :assert_extension_cleanup_called,
 :assert_extension_commands, :assert_extension_count, :assert_extension_error,
 :assert_extension_loaded, :assert_extension_tools, :assert_file_content,
 :assert_file_exists, :assert_file_has_bom, :assert_file_has_crlf,
 :assert_file_no_crlf, :assert_file_ops_contains, :assert_file_ops_text,
 :assert_follow_up_empty, :assert_follow_up_message, :assert_fork_cleaned,
 :assert_formatted_length, :assert_handoff_summary_not_empty,
 :assert_hook_blocked, :assert_hook_error_logged, :assert_hook_fired,
 :assert_jsonl_contains, :assert_jsonl_not_contains, :assert_last_call,
 :assert_last_call_nil, :assert_last_error, :assert_lock_race_result,
 :assert_model_count, :assert_model_error, :assert_model_list_count,
 :assert_model_string, :assert_no_compaction_error, :assert_no_crash,
 :assert_no_hook_error, :assert_no_retry, :assert_normalized_path,
 :assert_normalized_path_contains, :assert_normalized_path_is_absolute,
 :assert_not_compacted, :assert_output_contains, :assert_output_not_contains,
 :assert_parsed_thinking_error, :assert_parsed_thinking_level,
 :assert_partial_content, :assert_previous_summary,
 :assert_previous_summary_nil, :assert_prompt_contains, :assert_prompt_mode,
 :assert_prompt_text, :assert_provider_count, :assert_provider_current_nil,
 :assert_provider_error, :assert_provider_list_order, :assert_query_results,
 :assert_read_image, :assert_read_text, :assert_rendered_content,
 :assert_resource_content, :assert_resource_count,
 :assert_result_content_contains, :assert_result_content_not_contains,
 :assert_result_field, :assert_retry_happened, :assert_rpc_error,
 :assert_rpc_parsed, :assert_rpc_response_json, :assert_rpc_result,
 :assert_safe_execute_result, :assert_search_result_count,
 :assert_search_results, :assert_setting_nil, :assert_setting_value,
 :assert_settings_list, :assert_should_retry, :assert_steering_empty,
 :assert_steering_message, :assert_steering_message_nil,
 :assert_steering_not_pending, :assert_steering_pending,
 :assert_steering_skip_contains, :assert_stream_content, :assert_stream_events,
 :assert_summary_exists, :assert_summary_nil, :assert_system_preserved,
 :assert_tape_branches, :assert_tape_context_path, :assert_tape_error,
 :assert_tape_has_compaction_anchor, :assert_telemetry_received,
 :assert_telemetry_sequence, :assert_template_error, :assert_template_exists,
 :assert_template_list_count, :assert_template_variables,
 :assert_thinking_budget, :assert_thinking_invalid, :assert_thinking_params,
 :assert_thinking_params_empty, :assert_thinking_valid, :assert_token_estimate,
 :assert_token_estimate_value, :assert_token_expired, :assert_tool_error,
 :assert_tool_event_name, :assert_tool_event_sequence, :assert_tool_not_called,
 :assert_tool_pairs_intact, :assert_tool_success, :assert_tool_truncated,
 :assert_tool_was_called, :assert_truncation_notification,
 :assert_truncation_result, :attach_telemetry_handler, :auto_compact,
 :build_default_prompt, :build_handoff_summary, :build_summarize_prompt,
 :build_workspace_prompt, :check_e2e_provider, :check_token_expired,
 :classify_error, :cleanup_extension, :cleanup_model_registry,
 :cleanup_provider_registry, :cleanup_settings, :clear_file,
 :compaction_lock_acquired, :compaction_messages,
 :compaction_messages_with_summary, :compaction_messages_with_system,
 :compaction_messages_with_tool_calls, :compaction_messages_with_tools,
 :compaction_summarize_fn_fail, :compaction_summarize_fn_ok,
 :compaction_summarize_fn_raise, :concurrent_lock_acquire, :configure_agent,
 :configure_hooks, :convert_messages, :corrupt_jsonl, :create_binary_file,
 :create_bom_file, :create_extension_dir, :create_extension_file,
 :create_large_file, :create_png_file, :create_resource_dir,
 :create_resource_file, :create_settings_file, :create_symlink,
 :create_temp_dir, :create_temp_file, :cross_provider_messages,
 :cross_provider_multipart_message, :cross_provider_tool_calls_message,
 :delete_file, :detect_auth_method, :discover_extensions, :estimate_text,
 :exchange_auth_code, :execute_command, :execute_command_expect_error,
 :extract_file_operations, :extract_prompt_file_ops, :find_previous_summary,
 :format_conversation, :generate_authorize_url, :generate_branch_summary,
 :generate_content, :get_api_key, :get_model_string, :get_model_string_safe,
 :get_setting, :get_setting_safe, :get_template, :get_template_expect_error,
 :get_thinking_budget, :init_command_registry, :init_cost_tracker,
 :init_model_registry, :init_prompt_templates, :init_provider_registry,
 :init_settings, :inject_follow_up, :inject_steering, :list_models,
 :list_settings, :load_all_extensions, :load_extension, :load_resources,
 :load_resources_from_paths, :mock_llm_response, :mock_stream_response,
 :normalize_path, :parse_rpc_request, :parse_thinking_level,
 :prompt_messages_multi_tools, :prompt_messages_plain,
 :prompt_messages_with_long_content, :prompt_messages_with_summary,
 :provider_fallback, :provider_fallback_expect_error, :push_steering_message,
 :record_llm_call, :refresh_auth_token, :register_command, :register_hook,
 :register_model, :register_provider, :register_provider_with_invalid_config,
 :register_template, :reload_resources, :render_template, :reset_cost_tracker,
 :retry_delay, :retry_should_retry, :rpc_dispatch, :rpc_dispatch_missing,
 :rpc_dispatch_raise, :rpc_handle, :send_abort_signal, :set_file_permission,
 :set_setting, :set_var, :setup_abort_scenario, :steering_check,
 :steering_check_follow_up, :steering_check_steering, :steering_push,
 :steering_push_typed, :steering_queue_empty, :steering_skip_result,
 :stream_tool_chunks, :switch_model, :switch_provider,
 :switch_provider_expect_error, :tape_append, :tape_branch_from,
 :tape_build_context, :tape_close_db, :tape_fork, :tape_handoff, :tape_init,
 :tape_navigate, :tape_restore_parent, :thinking_to_provider, :tool_bash,
 :tool_edit, :tool_edit_diff, :tool_find, :tool_grep, :tool_ls, :tool_read,
 :tool_truncate, :tool_write, :trigger_compaction, :truncate_head,
 :truncate_line, :truncate_tail, :validate_model, :validate_thinking_level,
 :when_acquire_lock, :when_compact, :when_compact_and_handoff,
 :when_estimate_tokens, :when_release_lock, :when_tape_append,
 :when_tape_between_anchors, :when_tape_fork, :when_tape_handoff,
 :when_tape_init, :when_tape_merge, :when_tape_rebuild_index, :when_tape_search]