# Generated by bdd_compiler from docs/bdd/application.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ApplicationTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: APP-001
  @tag :application
  @tag :integration
  test "[APP-001] Application 启动初始化所有组件" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "APP-001"}
    # line 9: GIVEN application_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :application_started, %{}, %{file: "docs/bdd/application.dsl", line: 9, raw: "GIVEN application_started"}, 9)
    # line 10: THEN assert_registry_running name="Jido.Registry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_registry_running, %{name: "Jido.Registry"}, %{file: "docs/bdd/application.dsl", line: 10, raw: "THEN assert_registry_running name=\"Jido.Registry\""}, 10)
    # line 11: THEN assert_registry_running name="Gong.SessionRegistry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_registry_running, %{name: "Gong.SessionRegistry"}, %{file: "docs/bdd/application.dsl", line: 11, raw: "THEN assert_registry_running name=\"Gong.SessionRegistry\""}, 11)
    # line 12: THEN assert_supervisor_running name="Gong.SessionSupervisor"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_supervisor_running, %{name: "Gong.SessionSupervisor"}, %{file: "docs/bdd/application.dsl", line: 12, raw: "THEN assert_supervisor_running name=\"Gong.SessionSupervisor\""}, 12)
    # line 13: THEN assert_ets_table_exists name="gong_command_registry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_command_registry"}, %{file: "docs/bdd/application.dsl", line: 13, raw: "THEN assert_ets_table_exists name=\"gong_command_registry\""}, 13)
    # line 14: THEN assert_ets_table_exists name="gong_model_registry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_model_registry"}, %{file: "docs/bdd/application.dsl", line: 14, raw: "THEN assert_ets_table_exists name=\"gong_model_registry\""}, 14)
    # line 15: THEN assert_ets_table_exists name="gong_prompt_templates"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_prompt_templates"}, %{file: "docs/bdd/application.dsl", line: 15, raw: "THEN assert_ets_table_exists name=\"gong_prompt_templates\""}, 15)
    _ctx = ctx
    :ok
  end

  # Source: APP-002
  @tag :application
  @tag :integration
  test "[APP-002]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "APP-002"}
    # line 18: GIVEN application_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :application_started, %{}, %{file: "docs/bdd/application.dsl", line: 18, raw: "GIVEN application_started"}, 18)
    # line 19: THEN assert_ets_table_exists name="gong_command_registry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_command_registry"}, %{file: "docs/bdd/application.dsl", line: 19, raw: "THEN assert_ets_table_exists name=\"gong_command_registry\""}, 19)
    # line 20: THEN assert_ets_table_exists name="gong_model_registry"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_model_registry"}, %{file: "docs/bdd/application.dsl", line: 20, raw: "THEN assert_ets_table_exists name=\"gong_model_registry\""}, 20)
    # line 21: THEN assert_ets_table_exists name="gong_prompt_templates"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_ets_table_exists, %{name: "gong_prompt_templates"}, %{file: "docs/bdd/application.dsl", line: 21, raw: "THEN assert_ets_table_exists name=\"gong_prompt_templates\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: APP-003
  @tag :application
  @tag :integration
  test "[APP-003] Provider 注册成功" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "APP-003"}
    # line 24: GIVEN application_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :application_started, %{}, %{file: "docs/bdd/application.dsl", line: 24, raw: "GIVEN application_started"}, 24)
    # line 25: THEN assert_provider_registered name="Gong.Providers.DeepSeek"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_registered, %{name: "Gong.Providers.DeepSeek"}, %{file: "docs/bdd/application.dsl", line: 25, raw: "THEN assert_provider_registered name=\"Gong.Providers.DeepSeek\""}, 25)
    _ctx = ctx
    :ok
  end

  # Source: APP-004
  @tag :application
  @tag :unit
  test "[APP-004] Application 重复启动返回已启动" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "APP-004"}
    # line 32: GIVEN application_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :application_started, %{}, %{file: "docs/bdd/application.dsl", line: 32, raw: "GIVEN application_started"}, 32)
    # line 33: WHEN start_application
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :start_application, %{}, %{file: "docs/bdd/application.dsl", line: 33, raw: "WHEN start_application"}, 33)
    # line 34: THEN assert_application_already_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_application_already_started, %{}, %{file: "docs/bdd/application.dsl", line: 34, raw: "THEN assert_application_already_started"}, 34)
    _ctx = ctx
    :ok
  end

  # Source: APP-005
  @tag :application
  @tag :integration
  test "[APP-005] Application 停止后组件清理" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "APP-005"}
    # line 37: GIVEN application_started
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :application_started, %{}, %{file: "docs/bdd/application.dsl", line: 37, raw: "GIVEN application_started"}, 37)
    # line 38: WHEN stop_application
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :stop_application, %{}, %{file: "docs/bdd/application.dsl", line: 38, raw: "WHEN stop_application"}, 38)
    # line 39: THEN assert_no_session_processes
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_session_processes, %{}, %{file: "docs/bdd/application.dsl", line: 39, raw: "THEN assert_no_session_processes"}, 39)
    _ctx = ctx
    :ok
  end

end
