# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/auto_compaction.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.AutoCompactionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-AUTOCOMPACT-001
  @tag :agent_loop
  @tag :unit
  test "[BDD-AUTOCOMPACT-001] 上下文超限自动触发压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-AUTOCOMPACT-001"}
    # line 5: GIVEN compaction_messages count=20 token_size=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 20, token_size: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 5, raw: "GIVEN compaction_messages count=20 token_size=500"}, 5)
    # line 6: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 6, raw: "GIVEN compaction_summarize_fn_ok"}, 6)
    # line 7: WHEN auto_compact context_window=2000 reserve_tokens=500 window_size=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :auto_compact, %{context_window: 2000, reserve_tokens: 500, window_size: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 7, raw: "WHEN auto_compact context_window=2000 reserve_tokens=500 window_size=5"}, 7)
    # line 8: THEN assert_auto_compacted
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_auto_compacted, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 8, raw: "THEN assert_auto_compacted"}, 8)
    _ctx = ctx
    :ok
  end

  # Source: BDD-AUTOCOMPACT-002
  @tag :agent_loop
  @tag :unit
  test "[BDD-AUTOCOMPACT-002] 上下文未超限不压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-AUTOCOMPACT-002"}
    # line 11: GIVEN compaction_messages count=3 token_size=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 3, token_size: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 11, raw: "GIVEN compaction_messages count=3 token_size=10"}, 11)
    # line 12: WHEN auto_compact context_window=200000 reserve_tokens=16384 window_size=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :auto_compact, %{context_window: 200000, reserve_tokens: 16384, window_size: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 12, raw: "WHEN auto_compact context_window=200000 reserve_tokens=16384 window_size=5"}, 12)
    # line 13: THEN assert_auto_no_action
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_auto_no_action, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 13, raw: "THEN assert_auto_no_action"}, 13)
    _ctx = ctx
    :ok
  end

  # Source: BDD-AUTOCOMPACT-003
  @tag :agent_loop
  @tag :unit
  test "[BDD-AUTOCOMPACT-003] 压缩期间 steering 队列消息保留" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-AUTOCOMPACT-003"}
    # line 16: GIVEN steering_queue_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :steering_queue_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 16, raw: "GIVEN steering_queue_empty"}, 16)
    # line 17: GIVEN compaction_messages count=20 token_size=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 20, token_size: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 17, raw: "GIVEN compaction_messages count=20 token_size=500"}, 17)
    # line 18: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 18, raw: "GIVEN compaction_summarize_fn_ok"}, 18)
    # line 19: WHEN steering_push message="新用户消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :steering_push, %{message: "新用户消息"}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 19, raw: "WHEN steering_push message=\"新用户消息\""}, 19)
    # line 20: WHEN auto_compact context_window=2000 reserve_tokens=500 window_size=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :auto_compact, %{context_window: 2000, reserve_tokens: 500, window_size: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 20, raw: "WHEN auto_compact context_window=2000 reserve_tokens=500 window_size=5"}, 20)
    # line 21: THEN assert_auto_compacted
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_auto_compacted, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 21, raw: "THEN assert_auto_compacted"}, 21)
    # line 22: THEN assert_steering_pending
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_pending, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/auto_compaction.dsl", line: 22, raw: "THEN assert_steering_pending"}, 22)
    _ctx = ctx
    :ok
  end

end
