# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/bash_action.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.BashActionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-BASH-001
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-001] 简单命令" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-001"}
    # line 8: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 8, raw: "GIVEN create_temp_dir"}, 8)
    # line 9: WHEN tool_bash command="echo hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 9, raw: "WHEN tool_bash command=\"echo hello\""}, 9)
    # line 10: THEN assert_tool_success content_contains="hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 10, raw: "THEN assert_tool_success content_contains=\"hello\""}, 10)
    # line 11: THEN assert_exit_code expected=0
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_exit_code, %{expected: 0}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 11, raw: "THEN assert_exit_code expected=0"}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-002
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-002] 命令错误码" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-002"}
    # line 14: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 14, raw: "GIVEN create_temp_dir"}, 14)
    # line 15: WHEN tool_bash command="exit 1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "exit 1"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 15, raw: "WHEN tool_bash command=\"exit 1\""}, 15)
    # line 16: THEN assert_exit_code expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_exit_code, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 16, raw: "THEN assert_exit_code expected=1"}, 16)
    # line 17: THEN assert_output_contains text="exited with code 1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "exited with code 1"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 17, raw: "THEN assert_output_contains text=\"exited with code 1\""}, 17)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-003
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-003] 命令前缀环境变量" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-003"}
    # line 20: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 20, raw: "GIVEN create_temp_dir"}, 20)
    # line 21: WHEN tool_bash command="TEST_VAR=hello; echo $TEST_VAR"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "TEST_VAR=hello; echo $TEST_VAR"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 21, raw: "WHEN tool_bash command=\"TEST_VAR=hello; echo $TEST_VAR\""}, 21)
    # line 22: THEN assert_tool_success content_contains="hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 22, raw: "THEN assert_tool_success content_contains=\"hello\""}, 22)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-004
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-004] 多行输出" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-004"}
    # line 25: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 25, raw: "GIVEN create_temp_dir"}, 25)
    # line 26: WHEN tool_bash command="printf 'line1\nline2\nline3\n'"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "printf 'line1\\nline2\\nline3\\n'"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 26, raw: "WHEN tool_bash command=\"printf 'line1\\nline2\\nline3\\n'\""}, 26)
    # line 27: THEN assert_tool_success content_contains="line1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "line1"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 27, raw: "THEN assert_tool_success content_contains=\"line1\""}, 27)
    # line 28: THEN assert_output_contains text="line2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "line2"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 28, raw: "THEN assert_output_contains text=\"line2\""}, 28)
    # line 29: THEN assert_output_contains text="line3"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "line3"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 29, raw: "THEN assert_output_contains text=\"line3\""}, 29)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-005
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-005] 超时" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-005"}
    # line 34: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 34, raw: "GIVEN create_temp_dir"}, 34)
    # line 35: WHEN tool_bash command="sleep 10" timeout=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "sleep 10", timeout: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 35, raw: "WHEN tool_bash command=\"sleep 10\" timeout=1"}, 35)
    # line 36: THEN assert_output_contains text="timed out after 1 seconds"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "timed out after 1 seconds"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 36, raw: "THEN assert_output_contains text=\"timed out after 1 seconds\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-006
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-006] 不存在的工作目录" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-006"}
    # line 39: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 39, raw: "GIVEN create_temp_dir"}, 39)
    # line 40: WHEN tool_bash command="echo test" cwd="/this/directory/does/not/exist"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo test", cwd: "/this/directory/does/not/exist"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 40, raw: "WHEN tool_bash command=\"echo test\" cwd=\"/this/directory/does/not/exist\""}, 40)
    # line 41: THEN assert_tool_error error_contains="ENOENT"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error, %{error_contains: "ENOENT"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 41, raw: "THEN assert_tool_error error_contains=\"ENOENT\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-007
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-007] 空命令" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-007"}
    # line 44: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 44, raw: "GIVEN create_temp_dir"}, 44)
    # line 45: WHEN tool_bash command=""
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: ""}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 45, raw: "WHEN tool_bash command=\"\""}, 45)
    # line 46: THEN assert_tool_error error_contains="cannot be empty"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error, %{error_contains: "cannot be empty"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 46, raw: "THEN assert_tool_error error_contains=\"cannot be empty\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-008
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-008] stderr 和 stdout 合并" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-008"}
    # line 51: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 51, raw: "GIVEN create_temp_dir"}, 51)
    # line 52: WHEN tool_bash command="echo out; echo err >&2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo out; echo err >&2"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 52, raw: "WHEN tool_bash command=\"echo out; echo err >&2\""}, 52)
    # line 53: THEN assert_tool_success content_contains="out"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "out"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 53, raw: "THEN assert_tool_success content_contains=\"out\""}, 53)
    # line 54: THEN assert_output_contains text="err"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "err"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 54, raw: "THEN assert_output_contains text=\"err\""}, 54)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-009
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-009] 工作目录设置" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-009"}
    # line 57: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 57, raw: "GIVEN create_temp_dir"}, 57)
    # line 58: GIVEN create_temp_file path="subdir/marker.txt" content="found"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "found", path: "subdir/marker.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 58, raw: "GIVEN create_temp_file path=\"subdir/marker.txt\" content=\"found\""}, 58)
    # line 59: WHEN tool_bash command="cat marker.txt" cwd="subdir"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "cat marker.txt", cwd: "subdir"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 59, raw: "WHEN tool_bash command=\"cat marker.txt\" cwd=\"subdir\""}, 59)
    # line 60: THEN assert_tool_success content_contains="found"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "found"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 60, raw: "THEN assert_tool_success content_contains=\"found\""}, 60)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-010
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-010] bash 特有语法" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-010"}
    # line 65: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 65, raw: "GIVEN create_temp_dir"}, 65)
    # line 66: WHEN tool_bash command="if [[ -f /etc/hosts ]]; then echo yes; fi"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "if [[ -f /etc/hosts ]]; then echo yes; fi"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 66, raw: "WHEN tool_bash command=\"if [[ -f /etc/hosts ]]; then echo yes; fi\""}, 66)
    # line 67: THEN assert_tool_success content_contains="yes"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "yes"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 67, raw: "THEN assert_tool_success content_contains=\"yes\""}, 67)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-011
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-011] 管道命令" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-011"}
    # line 70: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 70, raw: "GIVEN create_temp_dir"}, 70)
    # line 71: WHEN tool_bash command="echo hello | tr 'h' 'H'"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo hello | tr 'h' 'H'"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 71, raw: "WHEN tool_bash command=\"echo hello | tr 'h' 'H'\""}, 71)
    # line 72: THEN assert_tool_success content_contains="Hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "Hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 72, raw: "THEN assert_tool_success content_contains=\"Hello\""}, 72)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-012
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-012] 环境变量继承" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-012"}
    # line 77: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 77, raw: "GIVEN create_temp_dir"}, 77)
    # line 78: WHEN tool_bash command="echo $HOME"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo $HOME"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 78, raw: "WHEN tool_bash command=\"echo $HOME\""}, 78)
    # line 79: THEN assert_tool_success
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 79, raw: "THEN assert_tool_success"}, 79)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-013
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-013] 命令不存在" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-013"}
    # line 82: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 82, raw: "GIVEN create_temp_dir"}, 82)
    # line 83: WHEN tool_bash command="nonexistent_command_xyz_123"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "nonexistent_command_xyz_123"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 83, raw: "WHEN tool_bash command=\"nonexistent_command_xyz_123\""}, 83)
    # line 84: THEN assert_exit_code expected=127
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_exit_code, %{expected: 127}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 84, raw: "THEN assert_exit_code expected=127"}, 84)
    _ctx = ctx
    :ok
  end

  # Source: BDD-BASH-014
  @tag :external_io
  @tag :unit
  test "[BDD-BASH-014] 返回值含 timed_out 标记" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-BASH-014"}
    # line 87: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 87, raw: "GIVEN create_temp_dir"}, 87)
    # line 88: WHEN tool_bash command="echo quick"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "echo quick"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 88, raw: "WHEN tool_bash command=\"echo quick\""}, 88)
    # line 89: THEN assert_tool_success
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 89, raw: "THEN assert_tool_success"}, 89)
    # line 90: THEN assert_result_field field="timed_out" expected="false"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_result_field, %{expected: "false", field: "timed_out"}, %{file: "/home/wangbo/document/gong/docs/bdd/bash_action.dsl", line: 90, raw: "THEN assert_result_field field=\"timed_out\" expected=\"false\""}, 90)
    _ctx = ctx
    :ok
  end

end
