# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/branch_summary.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.BranchSummaryTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BRANCHSUM-001
  @tag :branch_summary
  @tag :unit
  test "[BRANCHSUM-001] 切换分支时自动生成摘要" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BRANCHSUM-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 10, raw: "GIVEN tape_init"}, 10)
    # line 11: GIVEN tape_append kind="user" content="Hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "Hello", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 11, raw: "GIVEN tape_append kind=\"user\" content=\"Hello\""}, 11)
    # line 12: GIVEN tape_append kind="assistant" content="Hi there"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "Hi there", kind: "assistant"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 12, raw: "GIVEN tape_append kind=\"assistant\" content=\"Hi there\""}, 12)
    # line 13: GIVEN tape_handoff name="branch_a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "branch_a"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 13, raw: "GIVEN tape_handoff name=\"branch_a\""}, 13)
    # line 14: GIVEN tape_append kind="user" content="How are you?"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "How are you?", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 14, raw: "GIVEN tape_append kind=\"user\" content=\"How are you?\""}, 14)
    # line 15: GIVEN tape_append kind="assistant" content="I am fine"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "I am fine", kind: "assistant"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 15, raw: "GIVEN tape_append kind=\"assistant\" content=\"I am fine\""}, 15)
    # line 16: WHEN generate_branch_summary anchor="branch_a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :generate_branch_summary, %{anchor: "branch_a"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 16, raw: "WHEN generate_branch_summary anchor=\"branch_a\""}, 16)
    # line 17: THEN assert_branch_summary contains="How are you"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_branch_summary, %{contains: "How are you"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 17, raw: "THEN assert_branch_summary contains=\"How are you\""}, 17)
    _ctx = ctx
    :ok
  end

  # Source: BRANCHSUM-002
  @tag :branch_summary
  @tag :unit
  test "[BRANCHSUM-002] 摘要包含分支关键操作" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BRANCHSUM-002"}
    # line 20: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 20, raw: "GIVEN create_temp_dir"}, 20)
    # line 21: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 21, raw: "GIVEN tape_init"}, 21)
    # line 22: GIVEN tape_append kind="user" content="Write code"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "Write code", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 22, raw: "GIVEN tape_append kind=\"user\" content=\"Write code\""}, 22)
    # line 23: GIVEN tape_append kind="assistant" content="Here is the code"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "Here is the code", kind: "assistant"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 23, raw: "GIVEN tape_append kind=\"assistant\" content=\"Here is the code\""}, 23)
    # line 24: GIVEN tape_handoff name="code_branch"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "code_branch"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 24, raw: "GIVEN tape_handoff name=\"code_branch\""}, 24)
    # line 25: GIVEN tape_append kind="user" content="Run tests"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "Run tests", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 25, raw: "GIVEN tape_append kind=\"user\" content=\"Run tests\""}, 25)
    # line 26: GIVEN tape_append kind="tool_use" content="bash: ls -la"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "bash: ls -la", kind: "tool_use"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 26, raw: "GIVEN tape_append kind=\"tool_use\" content=\"bash: ls -la\""}, 26)
    # line 27: WHEN generate_branch_summary anchor="code_branch"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :generate_branch_summary, %{anchor: "code_branch"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 27, raw: "WHEN generate_branch_summary anchor=\"code_branch\""}, 27)
    # line 28: THEN assert_branch_summary contains="Run tests"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_branch_summary, %{contains: "Run tests"}, %{file: "/home/wangbo/document/gong/docs/bdd/branch_summary.dsl", line: 28, raw: "THEN assert_branch_summary contains=\"Run tests\""}, 28)
    _ctx = ctx
    :ok
  end

end
