# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/compaction.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.CompactionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-COMPACT-001
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-001] 中英文混合 token 估算" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-001"}
    # line 9: GIVEN compaction_messages count=5 token_size=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 5, token_size: 100}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 9, raw: "GIVEN compaction_messages count=5 token_size=100"}, 9)
    # line 10: WHEN when_estimate_tokens
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_estimate_tokens, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 10, raw: "WHEN when_estimate_tokens"}, 10)
    # line 11: THEN assert_token_estimate min=100 max=2000
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_token_estimate, %{max: 2000, min: 100}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 11, raw: "THEN assert_token_estimate min=100 max=2000"}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-002
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-002] 空消息列表返回 0" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-002"}
    # line 14: GIVEN compaction_messages count=0 token_size=0
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 0, token_size: 0}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 14, raw: "GIVEN compaction_messages count=0 token_size=0"}, 14)
    # line 15: WHEN when_estimate_tokens
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_estimate_tokens, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 15, raw: "WHEN when_estimate_tokens"}, 15)
    # line 16: THEN assert_token_estimate min=0 max=0
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_token_estimate, %{max: 0, min: 0}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 16, raw: "THEN assert_token_estimate min=0 max=0"}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-003
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-003] 未超阈值不压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-003"}
    # line 23: GIVEN compaction_messages count=3 token_size=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 3, token_size: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 23, raw: "GIVEN compaction_messages count=3 token_size=10"}, 23)
    # line 24: WHEN when_compact max_tokens=100000 window_size=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact, %{max_tokens: 100000, window_size: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 24, raw: "WHEN when_compact max_tokens=100000 window_size=5"}, 24)
    # line 25: THEN assert_not_compacted
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_not_compacted, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 25, raw: "THEN assert_not_compacted"}, 25)
    # line 26: THEN assert_summary_nil
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_nil, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 26, raw: "THEN assert_summary_nil"}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-004
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-004] 超阈值触发压缩保留最近 N 条" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-004"}
    # line 29: GIVEN compaction_messages count=10 token_size=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 10, token_size: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 29, raw: "GIVEN compaction_messages count=10 token_size=500"}, 29)
    # line 30: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 30, raw: "GIVEN compaction_summarize_fn_ok"}, 30)
    # line 31: WHEN when_compact max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 31, raw: "WHEN when_compact max_tokens=50 window_size=3"}, 31)
    # line 32: THEN assert_summary_exists
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_exists, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 32, raw: "THEN assert_summary_exists"}, 32)
    # line 33: THEN assert_compacted message_count=4
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_compacted, %{message_count: 4}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 33, raw: "THEN assert_compacted message_count=4"}, 33)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-005
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-005] 系统消息始终保留不被压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-005"}
    # line 36: GIVEN compaction_messages_with_system count=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages_with_system, %{count: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 36, raw: "GIVEN compaction_messages_with_system count=10"}, 36)
    # line 37: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 37, raw: "GIVEN compaction_summarize_fn_ok"}, 37)
    # line 38: WHEN when_compact max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 38, raw: "WHEN when_compact max_tokens=50 window_size=3"}, 38)
    # line 39: THEN assert_system_preserved
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_system_preserved, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 39, raw: "THEN assert_system_preserved"}, 39)
    # line 40: THEN assert_summary_exists
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_exists, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 40, raw: "THEN assert_summary_exists"}, 40)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-006
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-006] LLM 摘要失败回退到截断策略" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-006"}
    # line 47: GIVEN compaction_messages count=10 token_size=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 10, token_size: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 47, raw: "GIVEN compaction_messages count=10 token_size=500"}, 47)
    # line 48: GIVEN compaction_summarize_fn_fail
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_fail, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 48, raw: "GIVEN compaction_summarize_fn_fail"}, 48)
    # line 49: WHEN when_compact max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 49, raw: "WHEN when_compact max_tokens=50 window_size=3"}, 49)
    # line 50: THEN assert_summary_nil
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_nil, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 50, raw: "THEN assert_summary_nil"}, 50)
    # line 51: THEN assert_compacted message_count=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_compacted, %{message_count: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 51, raw: "THEN assert_compacted message_count=10"}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-007
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-007] 并发压缩被锁拒绝" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-007"}
    # line 54: GIVEN compaction_lock_acquired session_id="test-session-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_lock_acquired, %{session_id: "test-session-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 54, raw: "GIVEN compaction_lock_acquired session_id=\"test-session-1\""}, 54)
    # line 55: WHEN when_acquire_lock session_id="test-session-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_acquire_lock, %{session_id: "test-session-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 55, raw: "WHEN when_acquire_lock session_id=\"test-session-1\""}, 55)
    # line 56: THEN assert_compaction_error error_contains="compaction_in_progress"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_compaction_error, %{error_contains: "compaction_in_progress"}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 56, raw: "THEN assert_compaction_error error_contains=\"compaction_in_progress\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-COMPACT-008
  @tag :compaction
  @tag :unit
  test "[BDD-COMPACT-008]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-COMPACT-008"}
    # line 59: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 59, raw: "GIVEN create_temp_dir"}, 59)
    # line 60: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 60, raw: "GIVEN tape_init"}, 60)
    # line 61: GIVEN compaction_messages count=10 token_size=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages, %{count: 10, token_size: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 61, raw: "GIVEN compaction_messages count=10 token_size=500"}, 61)
    # line 62: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 62, raw: "GIVEN compaction_summarize_fn_ok"}, 62)
    # line 63: WHEN when_compact_and_handoff max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact_and_handoff, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 63, raw: "WHEN when_compact_and_handoff max_tokens=50 window_size=3"}, 63)
    # line 64: THEN assert_tape_has_compaction_anchor
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tape_has_compaction_anchor, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 64, raw: "THEN assert_tape_has_compaction_anchor"}, 64)
    # line 65: THEN assert_summary_exists
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_exists, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/compaction.dsl", line: 65, raw: "THEN assert_summary_exists"}, 65)
    _ctx = ctx
    :ok
  end

end
