# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/cost_edge.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.CostEdgeTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: COST-ERR-001
  @tag :retry
  @tag :unit
  test "[COST-ERR-001] 429 限流不触发压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: WHEN classify_error error="429 rate limit"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :classify_error, %{error: "429 rate limit"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 10, raw: "WHEN classify_error error=\"429 rate limit\""}, 10)
    # line 11: THEN assert_error_class expected="transient"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_error_class, %{expected: "transient"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 11, raw: "THEN assert_error_class expected=\"transient\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: COST-ERR-002
  @tag :retry
  @tag :unit
  test "[COST-ERR-002] context_length_exceeded 正确识别" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-002"}
    # line 14: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 14, raw: "GIVEN create_temp_dir"}, 14)
    # line 15: WHEN classify_error error="token count exceeds context window"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :classify_error, %{error: "token count exceeds context window"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 15, raw: "WHEN classify_error error=\"token count exceeds context window\""}, 15)
    # line 16: THEN assert_error_class expected="context_overflow"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_error_class, %{expected: "context_overflow"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 16, raw: "THEN assert_error_class expected=\"context_overflow\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: COST-ERR-003
  @tag :cost
  @tag :unit
  test "[COST-ERR-003] 流中断保留令牌计数" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-003"}
    # line 19: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 19, raw: "GIVEN create_temp_dir"}, 19)
    # line 20: WHEN init_cost_tracker
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_cost_tracker, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 20, raw: "WHEN init_cost_tracker"}, 20)
    # line 21: WHEN record_llm_call model="claude-3" input_tokens=100 output_tokens=50
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :record_llm_call, %{input_tokens: 100, model: "claude-3", output_tokens: 50}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 21, raw: "WHEN record_llm_call model=\"claude-3\" input_tokens=100 output_tokens=50"}, 21)
    # line 22: WHEN reset_cost_tracker
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :reset_cost_tracker, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 22, raw: "WHEN reset_cost_tracker"}, 22)
    # line 23: THEN assert_cost_summary call_count=0
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_cost_summary, %{call_count: 0}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 23, raw: "THEN assert_cost_summary call_count=0"}, 23)
    _ctx = ctx
    :ok
  end

  # Source: COST-ERR-004
  @tag :compaction
  @tag :unit
  test "[COST-ERR-004] 压缩 cut point 不越过 session header" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-004"}
    # line 30: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 30, raw: "GIVEN create_temp_dir"}, 30)
    # line 31: GIVEN compaction_messages_with_session_header count=8 header_at=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages_with_session_header, %{count: 8, header_at: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 31, raw: "GIVEN compaction_messages_with_session_header count=8 header_at=3"}, 31)
    # line 32: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 32, raw: "GIVEN compaction_summarize_fn_ok"}, 32)
    # line 33: WHEN when_compact max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_compact, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 33, raw: "WHEN when_compact max_tokens=50 window_size=3"}, 33)
    # line 34: THEN assert_compacted message_count=4
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_compacted, %{message_count: 4}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 34, raw: "THEN assert_compacted message_count=4"}, 34)
    # line 35: THEN assert_session_header_preserved
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_session_header_preserved, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 35, raw: "THEN assert_session_header_preserved"}, 35)
    _ctx = ctx
    :ok
  end

  # Source: COST-ERR-005
  @tag :compaction
  @tag :unit
  test "[COST-ERR-005] 分支摘要保留工具调用结构" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-005"}
    # line 38: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 38, raw: "GIVEN create_temp_dir"}, 38)
    # line 39: GIVEN compaction_messages_with_tool_calls count=6
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_messages_with_tool_calls, %{count: 6}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 39, raw: "GIVEN compaction_messages_with_tool_calls count=6"}, 39)
    # line 40: GIVEN compaction_summarize_fn_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :compaction_summarize_fn_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 40, raw: "GIVEN compaction_summarize_fn_ok"}, 40)
    # line 41: WHEN compact_with_tool_calls max_tokens=50 window_size=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :compact_with_tool_calls, %{max_tokens: 50, window_size: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 41, raw: "WHEN compact_with_tool_calls max_tokens=50 window_size=3"}, 41)
    # line 42: THEN assert_summary_has_tool_calls
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_summary_has_tool_calls, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 42, raw: "THEN assert_summary_has_tool_calls"}, 42)
    _ctx = ctx
    :ok
  end

  # Source: COST-ERR-006
  @tag :compaction
  @tag :unit
  test "[COST-ERR-006] 切换模型后旧模型 overflow 不误触发新模型压缩" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "COST-ERR-006"}
    # line 45: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 45, raw: "GIVEN create_temp_dir"}, 45)
    # line 46: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 46, raw: "GIVEN init_model_registry"}, 46)
    # line 47: GIVEN register_model name="old_model" provider="openai" model_id="gpt-4"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{model_id: "gpt-4", name: "old_model", provider: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 47, raw: "GIVEN register_model name=\"old_model\" provider=\"openai\" model_id=\"gpt-4\""}, 47)
    # line 48: GIVEN register_model name="new_model" provider="anthropic" model_id="claude-3"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{model_id: "claude-3", name: "new_model", provider: "anthropic"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 48, raw: "GIVEN register_model name=\"new_model\" provider=\"anthropic\" model_id=\"claude-3\""}, 48)
    # line 49: WHEN trigger_overflow_on_model model="old_model"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :trigger_overflow_on_model, %{model: "old_model"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 49, raw: "WHEN trigger_overflow_on_model model=\"old_model\""}, 49)
    # line 50: WHEN switch_model_after_overflow new_model="new_model"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_model_after_overflow, %{new_model: "new_model"}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 50, raw: "WHEN switch_model_after_overflow new_model=\"new_model\""}, 50)
    # line 51: THEN assert_no_compaction_on_new_model
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_compaction_on_new_model, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/cost_edge.dsl", line: 51, raw: "THEN assert_no_compaction_on_new_model"}, 51)
    _ctx = ctx
    :ok
  end

end
