# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/extension.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ExtensionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: EXTEND-001
  @tag :extension
  @tag :unit
  test "[EXTEND-001] 发现 .ex 文件" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 10, raw: "GIVEN create_extension_dir"}, 10)
    # line 11: GIVEN create_extension_file name="test_ext.ex" content="defmodule TestDiscoverExt do\n  use Gong.Extension\n  def name, do: \"test_discover\"\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule TestDiscoverExt do\\n  use Gong.Extension\\n  def name, do: \\\"test_discover\\\"\\nend", name: "test_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 11, raw: "GIVEN create_extension_file name=\"test_ext.ex\" content=\"defmodule TestDiscoverExt do\\n  use Gong.Extension\\n  def name, do: \\\"test_discover\\\"\\nend\""}, 11)
    # line 12: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 12, raw: "WHEN load_all_extensions"}, 12)
    # line 13: THEN assert_extension_count expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_count, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 13, raw: "THEN assert_extension_count expected=1"}, 13)
    # line 14: THEN assert_extension_loaded name="TestDiscoverExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "TestDiscoverExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 14, raw: "THEN assert_extension_loaded name=\"TestDiscoverExt\""}, 14)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-002
  @tag :extension
  @tag :unit
  test "[EXTEND-002] Hook 回调注册" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-002"}
    # line 17: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 17, raw: "GIVEN create_temp_dir"}, 17)
    # line 18: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 18, raw: "GIVEN create_extension_dir"}, 18)
    # line 19: GIVEN create_extension_file name="hook_ext.ex" content="defmodule HookExt do\n  use Gong.Extension\n  def name, do: \"hook_ext\"\n  def hooks, do: [Gong.TestHooks.AllowAll]\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule HookExt do\\n  use Gong.Extension\\n  def name, do: \\\"hook_ext\\\"\\n  def hooks, do: [Gong.TestHooks.AllowAll]\\nend", name: "hook_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 19, raw: "GIVEN create_extension_file name=\"hook_ext.ex\" content=\"defmodule HookExt do\\n  use Gong.Extension\\n  def name, do: \\\"hook_ext\\\"\\n  def hooks, do: [Gong.TestHooks.AllowAll]\\nend\""}, 19)
    # line 20: WHEN load_extension path="hook_ext.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_extension, %{path: "hook_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 20, raw: "WHEN load_extension path=\"hook_ext.ex\""}, 20)
    # line 21: THEN assert_extension_loaded name="HookExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "HookExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 21, raw: "THEN assert_extension_loaded name=\"HookExt\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-003
  @tag :extension
  @tag :unit
  test "[EXTEND-003] 自定义工具注册" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-003"}
    # line 24: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 24, raw: "GIVEN create_temp_dir"}, 24)
    # line 25: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 25, raw: "GIVEN create_extension_dir"}, 25)
    # line 26: GIVEN create_extension_file name="tool_ext.ex" content="defmodule ToolExt do\n  use Gong.Extension\n  def name, do: \"tool_ext\"\n  def tools, do: [Gong.Tools.Read]\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule ToolExt do\\n  use Gong.Extension\\n  def name, do: \\\"tool_ext\\\"\\n  def tools, do: [Gong.Tools.Read]\\nend", name: "tool_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 26, raw: "GIVEN create_extension_file name=\"tool_ext.ex\" content=\"defmodule ToolExt do\\n  use Gong.Extension\\n  def name, do: \\\"tool_ext\\\"\\n  def tools, do: [Gong.Tools.Read]\\nend\""}, 26)
    # line 27: WHEN load_extension path="tool_ext.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_extension, %{path: "tool_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 27, raw: "WHEN load_extension path=\"tool_ext.ex\""}, 27)
    # line 28: THEN assert_extension_loaded name="ToolExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "ToolExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 28, raw: "THEN assert_extension_loaded name=\"ToolExt\""}, 28)
    # line 29: THEN assert_extension_tools expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_tools, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 29, raw: "THEN assert_extension_tools expected=1"}, 29)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-004
  @tag :extension
  @tag :unit
  test "[EXTEND-004] 加载失败隔离" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-004"}
    # line 32: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 32, raw: "GIVEN create_temp_dir"}, 32)
    # line 33: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 33, raw: "GIVEN create_extension_dir"}, 33)
    # line 34: GIVEN create_extension_file name="bad_ext.ex" content="defmodule BadExt do\n  this is invalid syntax\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule BadExt do\\n  this is invalid syntax\\nend", name: "bad_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 34, raw: "GIVEN create_extension_file name=\"bad_ext.ex\" content=\"defmodule BadExt do\\n  this is invalid syntax\\nend\""}, 34)
    # line 35: GIVEN create_extension_file name="good_ext.ex" content="defmodule GoodExt do\n  use Gong.Extension\n  def name, do: \"good_ext\"\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule GoodExt do\\n  use Gong.Extension\\n  def name, do: \\\"good_ext\\\"\\nend", name: "good_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 35, raw: "GIVEN create_extension_file name=\"good_ext.ex\" content=\"defmodule GoodExt do\\n  use Gong.Extension\\n  def name, do: \\\"good_ext\\\"\\nend\""}, 35)
    # line 36: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 36, raw: "WHEN load_all_extensions"}, 36)
    # line 37: THEN assert_extension_count expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_count, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 37, raw: "THEN assert_extension_count expected=1"}, 37)
    # line 38: THEN assert_extension_loaded name="GoodExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "GoodExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 38, raw: "THEN assert_extension_loaded name=\"GoodExt\""}, 38)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-005
  @tag :extension
  @tag :unit
  test "[EXTEND-005] 多 Extension 加载" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-005"}
    # line 41: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 41, raw: "GIVEN create_temp_dir"}, 41)
    # line 42: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 42, raw: "GIVEN create_extension_dir"}, 42)
    # line 43: GIVEN create_extension_file name="ext_a.ex" content="defmodule ExtA do\n  use Gong.Extension\n  def name, do: \"ext_a\"\n  def tools, do: [Gong.Tools.Read]\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule ExtA do\\n  use Gong.Extension\\n  def name, do: \\\"ext_a\\\"\\n  def tools, do: [Gong.Tools.Read]\\nend", name: "ext_a.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 43, raw: "GIVEN create_extension_file name=\"ext_a.ex\" content=\"defmodule ExtA do\\n  use Gong.Extension\\n  def name, do: \\\"ext_a\\\"\\n  def tools, do: [Gong.Tools.Read]\\nend\""}, 43)
    # line 44: GIVEN create_extension_file name="ext_b.ex" content="defmodule ExtB do\n  use Gong.Extension\n  def name, do: \"ext_b\"\n  def tools, do: [Gong.Tools.Write]\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule ExtB do\\n  use Gong.Extension\\n  def name, do: \\\"ext_b\\\"\\n  def tools, do: [Gong.Tools.Write]\\nend", name: "ext_b.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 44, raw: "GIVEN create_extension_file name=\"ext_b.ex\" content=\"defmodule ExtB do\\n  use Gong.Extension\\n  def name, do: \\\"ext_b\\\"\\n  def tools, do: [Gong.Tools.Write]\\nend\""}, 44)
    # line 45: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 45, raw: "WHEN load_all_extensions"}, 45)
    # line 46: THEN assert_extension_count expected=2
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_count, %{expected: 2}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 46, raw: "THEN assert_extension_count expected=2"}, 46)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-006
  @tag :extension
  @tag :unit
  test "[EXTEND-006] Extension 生命周期" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-006"}
    # line 49: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 49, raw: "GIVEN create_temp_dir"}, 49)
    # line 50: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 50, raw: "GIVEN create_extension_dir"}, 50)
    # line 51: GIVEN create_extension_file name="lifecycle_ext.ex" content="defmodule LifecycleExt do\n  use Gong.Extension\n  def name, do: \"lifecycle\"\n  def init(_opts), do: {:ok, %{initialized: true}}\n  def cleanup(_state), do: :ok\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule LifecycleExt do\\n  use Gong.Extension\\n  def name, do: \\\"lifecycle\\\"\\n  def init(_opts), do: {:ok, %{initialized: true}}\\n  def cleanup(_state), do: :ok\\nend", name: "lifecycle_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 51, raw: "GIVEN create_extension_file name=\"lifecycle_ext.ex\" content=\"defmodule LifecycleExt do\\n  use Gong.Extension\\n  def name, do: \\\"lifecycle\\\"\\n  def init(_opts), do: {:ok, %{initialized: true}}\\n  def cleanup(_state), do: :ok\\nend\""}, 51)
    # line 52: WHEN load_extension path="lifecycle_ext.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_extension, %{path: "lifecycle_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 52, raw: "WHEN load_extension path=\"lifecycle_ext.ex\""}, 52)
    # line 53: THEN assert_extension_loaded name="LifecycleExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "LifecycleExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 53, raw: "THEN assert_extension_loaded name=\"LifecycleExt\""}, 53)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-007
  @tag :extension
  @tag :unit
  test "[EXTEND-007] 空 extensions 目录不崩溃" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-007"}
    # line 60: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 60, raw: "GIVEN create_temp_dir"}, 60)
    # line 61: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 61, raw: "GIVEN create_extension_dir"}, 61)
    # line 62: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 62, raw: "WHEN load_all_extensions"}, 62)
    # line 63: THEN assert_extension_count expected=0
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_count, %{expected: 0}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 63, raw: "THEN assert_extension_count expected=0"}, 63)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-008
  @tag :extension
  @tag :unit
  test "[EXTEND-008] Extension 重复加载幂等" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-008"}
    # line 66: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 66, raw: "GIVEN create_temp_dir"}, 66)
    # line 67: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 67, raw: "GIVEN create_extension_dir"}, 67)
    # line 68: GIVEN create_extension_file name="idempotent.ex" content="defmodule IdempotentExt do\n  use Gong.Extension\n  def name, do: \"idempotent\"\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule IdempotentExt do\\n  use Gong.Extension\\n  def name, do: \\\"idempotent\\\"\\nend", name: "idempotent.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 68, raw: "GIVEN create_extension_file name=\"idempotent.ex\" content=\"defmodule IdempotentExt do\\n  use Gong.Extension\\n  def name, do: \\\"idempotent\\\"\\nend\""}, 68)
    # line 69: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 69, raw: "WHEN load_all_extensions"}, 69)
    # line 70: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 70, raw: "WHEN load_all_extensions"}, 70)
    # line 71: THEN assert_extension_loaded name="IdempotentExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "IdempotentExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 71, raw: "THEN assert_extension_loaded name=\"IdempotentExt\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: EXTEND-009
  @tag :extension
  @tag :unit
  test "[EXTEND-009] Extension 无 name 回调处理" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXTEND-009"}
    # line 74: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 74, raw: "GIVEN create_temp_dir"}, 74)
    # line 75: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 75, raw: "GIVEN create_extension_dir"}, 75)
    # line 76: GIVEN create_extension_file name="noname.ex" content="defmodule NoNameExt do\n  use Gong.Extension\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule NoNameExt do\\n  use Gong.Extension\\nend", name: "noname.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 76, raw: "GIVEN create_extension_file name=\"noname.ex\" content=\"defmodule NoNameExt do\\n  use Gong.Extension\\nend\""}, 76)
    # line 77: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 77, raw: "WHEN load_all_extensions"}, 77)
    # line 78: THEN assert_extension_count expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_count, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/extension.dsl", line: 78, raw: "THEN assert_extension_count expected=1"}, 78)
    _ctx = ctx
    :ok
  end

end
