# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/file_edge.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.FileEdgeTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: FILE-ERR-001
  @tag :external_io
  @tag :unit
  test "[FILE-ERR-001] NFD/NFC Unicode 路径规范化" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "FILE-ERR-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN create_temp_file path="café.txt" content="hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "hello", path: "café.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 10, raw: "GIVEN create_temp_file path=\"café.txt\" content=\"hello\""}, 10)
    # line 11: WHEN tool_read path="café.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_read, %{path: "café.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 11, raw: "WHEN tool_read path=\"café.txt\""}, 11)
    # line 12: THEN assert_tool_success content_contains="hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 12, raw: "THEN assert_tool_success content_contains=\"hello\""}, 12)
    _ctx = ctx
    :ok
  end

  # Source: FILE-ERR-002
  @tag :external_io
  @tag :unit
  test "[FILE-ERR-002] CRLF 行尾编辑匹配" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "FILE-ERR-002"}
    # line 15: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 15, raw: "GIVEN create_temp_dir"}, 15)
    # line 16: GIVEN create_temp_file path="crlf.txt" content="hello\r\nworld\r\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "hello\\r\\nworld\\r\\n", path: "crlf.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 16, raw: "GIVEN create_temp_file path=\"crlf.txt\" content=\"hello\\r\\nworld\\r\\n\""}, 16)
    # line 17: WHEN tool_edit path="crlf.txt" old_string="hello" new_string="hi"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_edit, %{new_string: "hi", old_string: "hello", path: "crlf.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 17, raw: "WHEN tool_edit path=\"crlf.txt\" old_string=\"hello\" new_string=\"hi\""}, 17)
    # line 18: THEN assert_tool_success
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 18, raw: "THEN assert_tool_success"}, 18)
    # line 19: THEN assert_file_has_crlf path="crlf.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_file_has_crlf, %{path: "crlf.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 19, raw: "THEN assert_file_has_crlf path=\"crlf.txt\""}, 19)
    _ctx = ctx
    :ok
  end

  # Source: FILE-ERR-003
  @tag :external_io
  @tag :unit
  test "[FILE-ERR-003]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "FILE-ERR-003"}
    # line 22: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 22, raw: "GIVEN create_temp_dir"}, 22)
    # line 23: GIVEN create_bom_file path="bom.txt" content="hello world"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_bom_file, %{content: "hello world", path: "bom.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 23, raw: "GIVEN create_bom_file path=\"bom.txt\" content=\"hello world\""}, 23)
    # line 24: WHEN tool_edit path="bom.txt" old_string="hello" new_string="hi"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_edit, %{new_string: "hi", old_string: "hello", path: "bom.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 24, raw: "WHEN tool_edit path=\"bom.txt\" old_string=\"hello\" new_string=\"hi\""}, 24)
    # line 25: THEN assert_tool_success
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 25, raw: "THEN assert_tool_success"}, 25)
    # line 26: THEN assert_file_has_bom path="bom.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_file_has_bom, %{path: "bom.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/file_edge.dsl", line: 26, raw: "THEN assert_file_has_bom path=\"bom.txt\""}, 26)
    _ctx = ctx
    :ok
  end

end
