# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/grep_action.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.GrepActionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-GREP-001
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-001] 单文件搜索" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-001"}
    # line 7: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 7, raw: "GIVEN create_temp_dir"}, 7)
    # line 8: GIVEN create_temp_file path="test.txt" content="line1\nhello world\nline3\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "line1\\nhello world\\nline3\\n", path: "test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 8, raw: "GIVEN create_temp_file path=\"test.txt\" content=\"line1\\nhello world\\nline3\\n\""}, 8)
    # line 9: WHEN tool_grep pattern="hello" path="test.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{path: "test.txt", pattern: "hello"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 9, raw: "WHEN tool_grep pattern=\"hello\" path=\"test.txt\""}, 9)
    # line 10: THEN assert_tool_success content_contains="hello world"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "hello world"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 10, raw: "THEN assert_tool_success content_contains=\"hello world\""}, 10)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-002
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-002] 多文件目录搜索" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-002"}
    # line 13: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 13, raw: "GIVEN create_temp_dir"}, 13)
    # line 14: GIVEN create_temp_file path="a.txt" content="test match here\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "test match here\\n", path: "a.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 14, raw: "GIVEN create_temp_file path=\"a.txt\" content=\"test match here\\n\""}, 14)
    # line 15: GIVEN create_temp_file path="b.txt" content="no match\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "no match\\n", path: "b.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 15, raw: "GIVEN create_temp_file path=\"b.txt\" content=\"no match\\n\""}, 15)
    # line 16: GIVEN create_temp_file path="c.txt" content="another test line\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "another test line\\n", path: "c.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 16, raw: "GIVEN create_temp_file path=\"c.txt\" content=\"another test line\\n\""}, 16)
    # line 17: WHEN tool_grep pattern="test"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{pattern: "test"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 17, raw: "WHEN tool_grep pattern=\"test\""}, 17)
    # line 18: THEN assert_tool_success content_contains="a.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "a.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 18, raw: "THEN assert_tool_success content_contains=\"a.txt\""}, 18)
    # line 19: THEN assert_output_contains text="c.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "c.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 19, raw: "THEN assert_output_contains text=\"c.txt\""}, 19)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-003
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-003] 无匹配" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-003"}
    # line 22: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 22, raw: "GIVEN create_temp_dir"}, 22)
    # line 23: GIVEN create_temp_file path="test.txt" content="hello world\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "hello world\\n", path: "test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 23, raw: "GIVEN create_temp_file path=\"test.txt\" content=\"hello world\\n\""}, 23)
    # line 24: WHEN tool_grep pattern="nonexistent"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{pattern: "nonexistent"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 24, raw: "WHEN tool_grep pattern=\"nonexistent\""}, 24)
    # line 25: THEN assert_tool_success content_contains="No matches"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "No matches"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 25, raw: "THEN assert_tool_success content_contains=\"No matches\""}, 25)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-004
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-004] 正则表达式" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-004"}
    # line 30: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 30, raw: "GIVEN create_temp_dir"}, 30)
    # line 31: GIVEN create_temp_file path="code.txt" content="hello123\nhello456\nworld\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "hello123\\nhello456\\nworld\\n", path: "code.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 31, raw: "GIVEN create_temp_file path=\"code.txt\" content=\"hello123\\nhello456\\nworld\\n\""}, 31)
    # line 32: WHEN tool_grep pattern="hello[0-9]+"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{pattern: "hello[0-9]+"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 32, raw: "WHEN tool_grep pattern=\"hello[0-9]+\""}, 32)
    # line 33: THEN assert_tool_success content_contains="hello123"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "hello123"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 33, raw: "THEN assert_tool_success content_contains=\"hello123\""}, 33)
    # line 34: THEN assert_output_contains text="hello456"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_contains, %{text: "hello456"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 34, raw: "THEN assert_output_contains text=\"hello456\""}, 34)
    # line 35: THEN assert_output_not_contains text="world"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_not_contains, %{text: "world"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 35, raw: "THEN assert_output_not_contains text=\"world\""}, 35)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-005
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-005] 字面匹配模式" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-005"}
    # line 38: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 38, raw: "GIVEN create_temp_dir"}, 38)
    # line 39: GIVEN create_temp_file path="code.txt" content="foo.bar(baz)\nfooXbarX\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "foo.bar(baz)\\nfooXbarX\\n", path: "code.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 39, raw: "GIVEN create_temp_file path=\"code.txt\" content=\"foo.bar(baz)\\nfooXbarX\\n\""}, 39)
    # line 40: WHEN tool_grep pattern="foo.bar(" fixed_strings=true
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{fixed_strings: true, pattern: "foo.bar("}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 40, raw: "WHEN tool_grep pattern=\"foo.bar(\" fixed_strings=true"}, 40)
    # line 41: THEN assert_tool_success content_contains="foo.bar(baz)"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "foo.bar(baz)"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 41, raw: "THEN assert_tool_success content_contains=\"foo.bar(baz)\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-006
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-006] 大小写不敏感" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-006"}
    # line 44: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 44, raw: "GIVEN create_temp_dir"}, 44)
    # line 45: GIVEN create_temp_file path="test.txt" content="Hello World\nhello world\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "Hello World\\nhello world\\n", path: "test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 45, raw: "GIVEN create_temp_file path=\"test.txt\" content=\"Hello World\\nhello world\\n\""}, 45)
    # line 46: WHEN tool_grep pattern="HELLO" ignore_case=true
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{ignore_case: true, pattern: "HELLO"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 46, raw: "WHEN tool_grep pattern=\"HELLO\" ignore_case=true"}, 46)
    # line 47: THEN assert_tool_success content_contains="Hello World"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "Hello World"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 47, raw: "THEN assert_tool_success content_contains=\"Hello World\""}, 47)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-007
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-007] 上下文行数" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-007"}
    # line 50: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 50, raw: "GIVEN create_temp_dir"}, 50)
    # line 51: GIVEN create_temp_file path="test.txt" content="line1\nline2\ntarget\nline4\nline5\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "line1\\nline2\\ntarget\\nline4\\nline5\\n", path: "test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 51, raw: "GIVEN create_temp_file path=\"test.txt\" content=\"line1\\nline2\\ntarget\\nline4\\nline5\\n\""}, 51)
    # line 52: WHEN tool_grep pattern="target" context=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{context: 1, pattern: "target"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 52, raw: "WHEN tool_grep pattern=\"target\" context=1"}, 52)
    # line 53: THEN assert_tool_success content_contains="target"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "target"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 53, raw: "THEN assert_tool_success content_contains=\"target\""}, 53)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-008
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-008] files_with_matches 模式" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-008"}
    # line 58: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 58, raw: "GIVEN create_temp_dir"}, 58)
    # line 59: GIVEN create_temp_file path="match.txt" content="found it\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "found it\\n", path: "match.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 59, raw: "GIVEN create_temp_file path=\"match.txt\" content=\"found it\\n\""}, 59)
    # line 60: GIVEN create_temp_file path="no.txt" content="nothing\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "nothing\\n", path: "no.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 60, raw: "GIVEN create_temp_file path=\"no.txt\" content=\"nothing\\n\""}, 60)
    # line 61: WHEN tool_grep pattern="found" output_mode="files_with_matches"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{output_mode: "files_with_matches", pattern: "found"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 61, raw: "WHEN tool_grep pattern=\"found\" output_mode=\"files_with_matches\""}, 61)
    # line 62: THEN assert_tool_success content_contains="match.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "match.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 62, raw: "THEN assert_tool_success content_contains=\"match.txt\""}, 62)
    # line 63: THEN assert_output_not_contains text="no.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_not_contains, %{text: "no.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 63, raw: "THEN assert_output_not_contains text=\"no.txt\""}, 63)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-009
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-009] glob 文件过滤" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-009"}
    # line 66: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 66, raw: "GIVEN create_temp_dir"}, 66)
    # line 67: GIVEN create_temp_file path="code.ex" content="test content\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "test content\\n", path: "code.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 67, raw: "GIVEN create_temp_file path=\"code.ex\" content=\"test content\\n\""}, 67)
    # line 68: GIVEN create_temp_file path="code.js" content="test content\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "test content\\n", path: "code.js"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 68, raw: "GIVEN create_temp_file path=\"code.js\" content=\"test content\\n\""}, 68)
    # line 69: WHEN tool_grep pattern="test" glob="*.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{glob: "*.ex", pattern: "test"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 69, raw: "WHEN tool_grep pattern=\"test\" glob=\"*.ex\""}, 69)
    # line 70: THEN assert_tool_success content_contains="code.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "code.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 70, raw: "THEN assert_tool_success content_contains=\"code.ex\""}, 70)
    # line 71: THEN assert_output_not_contains text="code.js"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_output_not_contains, %{text: "code.js"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 71, raw: "THEN assert_output_not_contains text=\"code.js\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-010
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-010] 二进制文件自动跳过" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-010"}
    # line 74: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 74, raw: "GIVEN create_temp_dir"}, 74)
    # line 75: GIVEN create_temp_file path="text.txt" content="search target\n"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "search target\\n", path: "text.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 75, raw: "GIVEN create_temp_file path=\"text.txt\" content=\"search target\\n\""}, 75)
    # line 76: GIVEN create_binary_file path="binary.bin" bytes=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_binary_file, %{bytes: 100, path: "binary.bin"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 76, raw: "GIVEN create_binary_file path=\"binary.bin\" bytes=100"}, 76)
    # line 77: WHEN tool_grep pattern="search"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{pattern: "search"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 77, raw: "WHEN tool_grep pattern=\"search\""}, 77)
    # line 78: THEN assert_tool_success content_contains="text.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_success, %{content_contains: "text.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 78, raw: "THEN assert_tool_success content_contains=\"text.txt\""}, 78)
    _ctx = ctx
    :ok
  end

  # Source: BDD-GREP-011
  @tag :external_io
  @tag :unit
  test "[BDD-GREP-011] 搜索路径不存在" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-GREP-011"}
    # line 83: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 83, raw: "GIVEN create_temp_dir"}, 83)
    # line 84: WHEN tool_grep pattern="test" path="nonexistent_dir"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_grep, %{path: "nonexistent_dir", pattern: "test"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 84, raw: "WHEN tool_grep pattern=\"test\" path=\"nonexistent_dir\""}, 84)
    # line 85: THEN assert_tool_error error_contains="ENOENT"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error, %{error_contains: "ENOENT"}, %{file: "/home/wangbo/document/gong/docs/bdd/grep_action.dsl", line: 85, raw: "THEN assert_tool_error error_contains=\"ENOENT\""}, 85)
    _ctx = ctx
    :ok
  end

end
