# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/hook_edge.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.HookEdgeTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: EXT-ERR-001
  @tag :hook
  @tag :integration
  test "[EXT-ERR-001] 多扩展 hook 链式执行" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN create_temp_file path="chain.txt" content="链式测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "链式测试", path: "chain.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 10, raw: "GIVEN create_temp_file path=\"chain.txt\" content=\"链式测试\""}, 10)
    # line 11: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 11, raw: "GIVEN configure_agent model=\"mock\""}, 11)
    # line 12: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 12, raw: "GIVEN register_hook module=\"AllowAll\""}, 12)
    # line 13: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 13, raw: "GIVEN register_hook module=\"AllowAll\""}, 13)
    # line 14: GIVEN attach_telemetry_handler event="gong.tool.start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :attach_telemetry_handler, %{event: "gong.tool.start"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 14, raw: "GIVEN attach_telemetry_handler event=\"gong.tool.start\""}, 14)
    # line 15: GIVEN mock_llm_response response_type="tool_call" tool="read_file" tool_args="file_path={{workspace}}/chain.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "read_file", tool_args: "file_path={{workspace}}/chain.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 15, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"read_file\" tool_args=\"file_path={{workspace}}/chain.txt\""}, 15)
    # line 16: GIVEN mock_llm_response response_type="text" content="链式完成"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "链式完成", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 16, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"链式完成\""}, 16)
    # line 17: WHEN agent_chat prompt="读取文件"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "读取文件"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 17, raw: "WHEN agent_chat prompt=\"读取文件\""}, 17)
    # line 18: THEN assert_agent_reply contains="链式完成"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "链式完成"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 18, raw: "THEN assert_agent_reply contains=\"链式完成\""}, 18)
    # line 19: THEN assert_hook_fired event="gong.tool.start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_hook_fired, %{event: "gong.tool.start"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 19, raw: "THEN assert_hook_fired event=\"gong.tool.start\""}, 19)
    _ctx = ctx
    :ok
  end

  # Source: EXT-ERR-002
  @tag :extension
  @tag :unit
  test "[EXT-ERR-002] 符号链接扩展能被发现" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-002"}
    # line 22: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 22, raw: "GIVEN create_temp_dir"}, 22)
    # line 23: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 23, raw: "GIVEN create_extension_dir"}, 23)
    # line 24: GIVEN create_extension_file name="real_ext.ex" content="defmodule SymlinkExt do\n  use Gong.Extension\n  def name, do: \"symlink_ext\"\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule SymlinkExt do\\n  use Gong.Extension\\n  def name, do: \\\"symlink_ext\\\"\\nend", name: "real_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 24, raw: "GIVEN create_extension_file name=\"real_ext.ex\" content=\"defmodule SymlinkExt do\\n  use Gong.Extension\\n  def name, do: \\\"symlink_ext\\\"\\nend\""}, 24)
    # line 25: GIVEN create_symlink link="extensions/link_ext.ex" target="extensions/real_ext.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_symlink, %{link: "extensions/link_ext.ex", target: "extensions/real_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 25, raw: "GIVEN create_symlink link=\"extensions/link_ext.ex\" target=\"extensions/real_ext.ex\""}, 25)
    # line 26: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 26, raw: "WHEN load_all_extensions"}, 26)
    # line 27: THEN assert_extension_loaded name="SymlinkExt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_loaded, %{name: "SymlinkExt"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 27, raw: "THEN assert_extension_loaded name=\"SymlinkExt\""}, 27)
    _ctx = ctx
    :ok
  end

  # Source: EXT-ERR-003
  @tag :extension
  @tag :unit
  test "[EXT-ERR-003] 扩展冲突时有明确错误提示" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-003"}
    # line 30: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 30, raw: "GIVEN create_temp_dir"}, 30)
    # line 31: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 31, raw: "GIVEN create_extension_dir"}, 31)
    # line 32: GIVEN create_conflicting_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_conflicting_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 32, raw: "GIVEN create_conflicting_extensions"}, 32)
    # line 33: WHEN load_all_extensions
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_all_extensions, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 33, raw: "WHEN load_all_extensions"}, 33)
    # line 34: THEN assert_extension_conflict_error error_contains="conflict"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_extension_conflict_error, %{error_contains: "conflict"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 34, raw: "THEN assert_extension_conflict_error error_contains=\"conflict\""}, 34)
    _ctx = ctx
    :ok
  end

  # Source: EXT-ERR-004
  @tag :hook
  @tag :integration
  test "[EXT-ERR-004] Hook 接收的 messages 是深拷贝" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-004"}
    # line 41: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 41, raw: "GIVEN create_temp_dir"}, 41)
    # line 42: GIVEN create_temp_file path="test.txt" content="深拷贝测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "深拷贝测试", path: "test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 42, raw: "GIVEN create_temp_file path=\"test.txt\" content=\"深拷贝测试\""}, 42)
    # line 43: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 43, raw: "GIVEN configure_agent model=\"mock\""}, 43)
    # line 44: GIVEN register_hook module="MessageMutatorHook"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "MessageMutatorHook"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 44, raw: "GIVEN register_hook module=\"MessageMutatorHook\""}, 44)
    # line 45: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 45, raw: "GIVEN register_hook module=\"AllowAll\""}, 45)
    # line 46: GIVEN mock_llm_response response_type="tool_call" tool="read_file" tool_args="file_path={{workspace}}/test.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "read_file", tool_args: "file_path={{workspace}}/test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 46, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"read_file\" tool_args=\"file_path={{workspace}}/test.txt\""}, 46)
    # line 47: GIVEN mock_llm_response response_type="text" content="深拷贝正常"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "深拷贝正常", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 47, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"深拷贝正常\""}, 47)
    # line 48: WHEN agent_chat prompt="测试深拷贝"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "测试深拷贝"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 48, raw: "WHEN agent_chat prompt=\"测试深拷贝\""}, 48)
    # line 49: THEN assert_agent_reply contains="深拷贝正常"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "深拷贝正常"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 49, raw: "THEN assert_agent_reply contains=\"深拷贝正常\""}, 49)
    _ctx = ctx
    :ok
  end

  # Source: EXT-ERR-005
  @tag :extension
  @tag :unit
  test "[EXT-ERR-005] 扩展禁用标志在所有代码路径生效" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-005"}
    # line 52: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 52, raw: "GIVEN create_temp_dir"}, 52)
    # line 53: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 53, raw: "GIVEN create_extension_dir"}, 53)
    # line 54: GIVEN create_extension_file name="test_ext.ex" content="defmodule TestFlagExt do\n  use Gong.Extension\n  def name, do: \"test_flag_ext\"\nend"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_file, %{content: "defmodule TestFlagExt do\\n  use Gong.Extension\\n  def name, do: \\\"test_flag_ext\\\"\\nend", name: "test_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 54, raw: "GIVEN create_extension_file name=\"test_ext.ex\" content=\"defmodule TestFlagExt do\\n  use Gong.Extension\\n  def name, do: \\\"test_flag_ext\\\"\\nend\""}, 54)
    # line 55: GIVEN set_no_extensions_flag
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_no_extensions_flag, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 55, raw: "GIVEN set_no_extensions_flag"}, 55)
    # line 56: WHEN discover_extensions_with_flag
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :discover_extensions_with_flag, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 56, raw: "WHEN discover_extensions_with_flag"}, 56)
    # line 57: THEN assert_no_extensions_loaded
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_extensions_loaded, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 57, raw: "THEN assert_no_extensions_loaded"}, 57)
    _ctx = ctx
    :ok
  end

  # Source: EXT-ERR-006
  @tag :extension
  @tag :unit
  test "[EXT-ERR-006] Custom tool 子路径 import 正确解析" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "EXT-ERR-006"}
    # line 60: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 60, raw: "GIVEN create_temp_dir"}, 60)
    # line 61: GIVEN create_extension_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 61, raw: "GIVEN create_extension_dir"}, 61)
    # line 62: GIVEN create_extension_with_import name="import_ext.ex" import_path="./helpers/utils.ex"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_extension_with_import, %{import_path: "./helpers/utils.ex", name: "import_ext.ex"}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 62, raw: "GIVEN create_extension_with_import name=\"import_ext.ex\" import_path=\"./helpers/utils.ex\""}, 62)
    # line 63: WHEN load_extension_with_imports
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :load_extension_with_imports, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 63, raw: "WHEN load_extension_with_imports"}, 63)
    # line 64: THEN assert_import_resolved
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_import_resolved, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/hook_edge.dsl", line: 64, raw: "THEN assert_import_resolved"}, 64)
    _ctx = ctx
    :ok
  end

end
