# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/model_registry.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ModelRegistryTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: MODEL-001
  @tag :model
  @tag :unit
  test "[MODEL-001] 默认模型配置" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-001"}
    # line 9: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 9, raw: "GIVEN init_model_registry"}, 9)
    # line 10: THEN assert_current_model name="default"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_model, %{name: "default"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 10, raw: "THEN assert_current_model name=\"default\""}, 10)
    _ctx = ctx
    :ok
  end

  # Source: MODEL-002
  @tag :model
  @tag :unit
  test "[MODEL-002] 运行时切换" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-002"}
    # line 13: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 13, raw: "GIVEN init_model_registry"}, 13)
    # line 14: GIVEN register_model name="model_a" provider="deepseek" model_id="deepseek-chat" api_key_env="DEEPSEEK_API_KEY"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "DEEPSEEK_API_KEY", model_id: "deepseek-chat", name: "model_a", provider: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 14, raw: "GIVEN register_model name=\"model_a\" provider=\"deepseek\" model_id=\"deepseek-chat\" api_key_env=\"DEEPSEEK_API_KEY\""}, 14)
    # line 15: GIVEN register_model name="model_b" provider="openai" model_id="gpt-4o" api_key_env="OPENAI_API_KEY"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "OPENAI_API_KEY", model_id: "gpt-4o", name: "model_b", provider: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 15, raw: "GIVEN register_model name=\"model_b\" provider=\"openai\" model_id=\"gpt-4o\" api_key_env=\"OPENAI_API_KEY\""}, 15)
    # line 16: WHEN switch_model name="model_b"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_model, %{name: "model_b"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 16, raw: "WHEN switch_model name=\"model_b\""}, 16)
    # line 17: THEN assert_current_model name="model_b"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_model, %{name: "model_b"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 17, raw: "THEN assert_current_model name=\"model_b\""}, 17)
    _ctx = ctx
    :ok
  end

  # Source: MODEL-003
  @tag :model
  @tag :unit
  test "[MODEL-003] 无效模型回退" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-003"}
    # line 20: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 20, raw: "GIVEN init_model_registry"}, 20)
    # line 21: WHEN switch_model name="nonexistent"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_model, %{name: "nonexistent"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 21, raw: "WHEN switch_model name=\"nonexistent\""}, 21)
    # line 22: THEN assert_current_model name="default"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_model, %{name: "default"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 22, raw: "THEN assert_current_model name=\"default\""}, 22)
    # line 23: THEN assert_model_error error_contains="not_found"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_model_error, %{error_contains: "not_found"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 23, raw: "THEN assert_model_error error_contains=\"not_found\""}, 23)
    _ctx = ctx
    :ok
  end

  # Source: MODEL-004
  @tag :model
  @tag :unit
  test "[MODEL-004] API Key 缺失" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-004"}
    # line 26: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 26, raw: "GIVEN init_model_registry"}, 26)
    # line 27: GIVEN register_model name="no_key" provider="openai" model_id="gpt-4o" api_key_env="GONG_TEST_NONEXISTENT_KEY_12345"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "GONG_TEST_NONEXISTENT_KEY_12345", model_id: "gpt-4o", name: "no_key", provider: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 27, raw: "GIVEN register_model name=\"no_key\" provider=\"openai\" model_id=\"gpt-4o\" api_key_env=\"GONG_TEST_NONEXISTENT_KEY_12345\""}, 27)
    # line 28: WHEN validate_model name="no_key"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :validate_model, %{name: "no_key"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 28, raw: "WHEN validate_model name=\"no_key\""}, 28)
    # line 29: THEN assert_model_error error_contains="未设置"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_model_error, %{error_contains: "未设置"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 29, raw: "THEN assert_model_error error_contains=\"未设置\""}, 29)
    _ctx = ctx
    :ok
  end

  # Source: MODEL-005
  @tag :model
  @tag :unit
  test "[MODEL-005] 多 Provider 注册" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-005"}
    # line 32: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 32, raw: "GIVEN init_model_registry"}, 32)
    # line 33: GIVEN register_model name="ds" provider="deepseek" model_id="deepseek-chat" api_key_env="DEEPSEEK_API_KEY"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "DEEPSEEK_API_KEY", model_id: "deepseek-chat", name: "ds", provider: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 33, raw: "GIVEN register_model name=\"ds\" provider=\"deepseek\" model_id=\"deepseek-chat\" api_key_env=\"DEEPSEEK_API_KEY\""}, 33)
    # line 34: GIVEN register_model name="oai" provider="openai" model_id="gpt-4o" api_key_env="OPENAI_API_KEY"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "OPENAI_API_KEY", model_id: "gpt-4o", name: "oai", provider: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 34, raw: "GIVEN register_model name=\"oai\" provider=\"openai\" model_id=\"gpt-4o\" api_key_env=\"OPENAI_API_KEY\""}, 34)
    # line 35: THEN assert_model_count expected=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_model_count, %{expected: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 35, raw: "THEN assert_model_count expected=3"}, 35)
    _ctx = ctx
    :ok
  end

  # Source: MODEL-006
  @tag :e2e
  @tag :model
  @tag :unit
  test "[MODEL-006] E2E 真实切换" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "MODEL-006"}
    # line 38: GIVEN check_e2e_provider
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :check_e2e_provider, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 38, raw: "GIVEN check_e2e_provider"}, 38)
    # line 39: GIVEN init_model_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_model_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 39, raw: "GIVEN init_model_registry"}, 39)
    # line 40: GIVEN register_model name="live" provider="deepseek" model_id="deepseek-chat" api_key_env="DEEPSEEK_API_KEY"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_model, %{api_key_env: "DEEPSEEK_API_KEY", model_id: "deepseek-chat", name: "live", provider: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 40, raw: "GIVEN register_model name=\"live\" provider=\"deepseek\" model_id=\"deepseek-chat\" api_key_env=\"DEEPSEEK_API_KEY\""}, 40)
    # line 41: WHEN switch_model name="live"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_model, %{name: "live"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 41, raw: "WHEN switch_model name=\"live\""}, 41)
    # line 42: THEN assert_current_model name="live"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_model, %{name: "live"}, %{file: "/home/wangbo/document/gong/docs/bdd/model_registry.dsl", line: 42, raw: "THEN assert_current_model name=\"live\""}, 42)
    _ctx = ctx
    :ok
  end

end
