# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/partial_json.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.PartialJsonTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: PJSON-001
  @tag :partial_json
  @tag :unit
  test "[PJSON-001] 完整 JSON 直接解析" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-001"}
    # line 5: WHEN partial_json_parse input="{\"a\":1}"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"a\\\":1}"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 5, raw: "WHEN partial_json_parse input=\"{\\\"a\\\":1}\""}, 5)
    # line 6: THEN assert_partial_json_ok
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_ok, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 6, raw: "THEN assert_partial_json_ok"}, 6)
    # line 7: THEN assert_partial_json_field key="a" expected="1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_field, %{expected: "1", key: "a"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 7, raw: "THEN assert_partial_json_field key=\"a\" expected=\"1\""}, 7)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-002
  @tag :partial_json
  @tag :unit
  test "[PJSON-002] 未闭合字符串补全" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-002"}
    # line 10: WHEN partial_json_parse input="{\"file\":\"/src/ma"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"file\\\":\\\"/src/ma"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 10, raw: "WHEN partial_json_parse input=\"{\\\"file\\\":\\\"/src/ma\""}, 10)
    # line 11: THEN assert_partial_json_has_key key="file"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "file"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 11, raw: "THEN assert_partial_json_has_key key=\"file\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-003
  @tag :partial_json
  @tag :unit
  test "[PJSON-003] 未闭合对象补全" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-003"}
    # line 14: WHEN partial_json_parse input="{\"a\":1,\"b\":2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"a\\\":1,\\\"b\\\":2"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 14, raw: "WHEN partial_json_parse input=\"{\\\"a\\\":1,\\\"b\\\":2\""}, 14)
    # line 15: THEN assert_partial_json_has_key key="a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "a"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 15, raw: "THEN assert_partial_json_has_key key=\"a\""}, 15)
    # line 16: THEN assert_partial_json_has_key key="b"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "b"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 16, raw: "THEN assert_partial_json_has_key key=\"b\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-004
  @tag :partial_json
  @tag :unit
  test "[PJSON-004] 嵌套对象补全" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-004"}
    # line 19: WHEN partial_json_parse input="{\"outer\":{\"inner\":1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"outer\\\":{\\\"inner\\\":1"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 19, raw: "WHEN partial_json_parse input=\"{\\\"outer\\\":{\\\"inner\\\":1\""}, 19)
    # line 20: THEN assert_partial_json_has_key key="outer"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "outer"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 20, raw: "THEN assert_partial_json_has_key key=\"outer\""}, 20)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-005
  @tag :partial_json
  @tag :unit
  test "[PJSON-005] 数组补全" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-005"}
    # line 23: WHEN partial_json_parse input="{\"items\":[1,2,3"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"items\\\":[1,2,3"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 23, raw: "WHEN partial_json_parse input=\"{\\\"items\\\":[1,2,3\""}, 23)
    # line 24: THEN assert_partial_json_has_key key="items"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "items"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 24, raw: "THEN assert_partial_json_has_key key=\"items\""}, 24)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-006
  @tag :partial_json
  @tag :unit
  test "[PJSON-006] 空输入返回空 map" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-006"}
    # line 27: WHEN partial_json_parse input=""
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: ""}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 27, raw: "WHEN partial_json_parse input=\"\""}, 27)
    # line 28: THEN assert_partial_json_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 28, raw: "THEN assert_partial_json_empty"}, 28)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-007
  @tag :partial_json
  @tag :unit
  test "[PJSON-007] 累积多片段合并" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-007"}
    # line 31: WHEN partial_json_accumulate chunk1="{%name%:%he" chunk2="llo" chunk3="%}"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_accumulate, %{chunk1: "{%name%:%he", chunk2: "llo", chunk3: "%}"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 31, raw: "WHEN partial_json_accumulate chunk1=\"{%name%:%he\" chunk2=\"llo\" chunk3=\"%}\""}, 31)
    # line 32: THEN assert_partial_json_field key="name" expected="hello"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_field, %{expected: "hello", key: "name"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 32, raw: "THEN assert_partial_json_field key=\"name\" expected=\"hello\""}, 32)
    _ctx = ctx
    :ok
  end

  # Source: PJSON-008
  @tag :partial_json
  @tag :unit
  test "[PJSON-008] 尾部逗号容错" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PJSON-008"}
    # line 35: WHEN partial_json_parse input="{\"a\":1,"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :partial_json_parse, %{input: "{\\\"a\\\":1,"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 35, raw: "WHEN partial_json_parse input=\"{\\\"a\\\":1,\""}, 35)
    # line 36: THEN assert_partial_json_has_key key="a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_partial_json_has_key, %{key: "a"}, %{file: "/home/wangbo/document/gong/docs/bdd/partial_json.dsl", line: 36, raw: "THEN assert_partial_json_has_key key=\"a\""}, 36)
    _ctx = ctx
    :ok
  end

end
