# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/provider.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ProviderTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: PROVIDER-001
  @tag :provider
  @tag :unit
  test "[PROVIDER-001] 注册单个 Provider" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 10, raw: "WHEN init_provider_registry"}, 10)
    # line 11: WHEN register_provider name="deepseek" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 11, raw: "WHEN register_provider name=\"deepseek\" module=\"MockProvider\""}, 11)
    # line 12: THEN assert_provider_count expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_count, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 12, raw: "THEN assert_provider_count expected=1"}, 12)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-002
  @tag :provider
  @tag :unit
  test "[PROVIDER-002] 注册多个 Provider" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-002"}
    # line 15: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 15, raw: "GIVEN create_temp_dir"}, 15)
    # line 16: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 16, raw: "WHEN init_provider_registry"}, 16)
    # line 17: WHEN register_provider name="deepseek" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 17, raw: "WHEN register_provider name=\"deepseek\" module=\"MockProvider\""}, 17)
    # line 18: WHEN register_provider name="openai" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 18, raw: "WHEN register_provider name=\"openai\" module=\"MockProvider\""}, 18)
    # line 19: WHEN register_provider name="anthropic" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "anthropic"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 19, raw: "WHEN register_provider name=\"anthropic\" module=\"MockProvider\""}, 19)
    # line 20: THEN assert_provider_count expected=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_count, %{expected: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 20, raw: "THEN assert_provider_count expected=3"}, 20)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-003
  @tag :provider
  @tag :unit
  test "[PROVIDER-003] 切换当前 Provider" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-003"}
    # line 23: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 23, raw: "GIVEN create_temp_dir"}, 23)
    # line 24: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 24, raw: "WHEN init_provider_registry"}, 24)
    # line 25: WHEN register_provider name="deepseek" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 25, raw: "WHEN register_provider name=\"deepseek\" module=\"MockProvider\""}, 25)
    # line 26: WHEN register_provider name="openai" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 26, raw: "WHEN register_provider name=\"openai\" module=\"MockProvider\""}, 26)
    # line 27: WHEN switch_provider name="openai"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_provider, %{name: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 27, raw: "WHEN switch_provider name=\"openai\""}, 27)
    # line 28: THEN assert_current_provider expected="openai"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_provider, %{expected: "openai"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 28, raw: "THEN assert_current_provider expected=\"openai\""}, 28)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-004
  @tag :provider
  @tag :unit
  test "[PROVIDER-004] 切换不存在的 Provider" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-004"}
    # line 31: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 31, raw: "GIVEN create_temp_dir"}, 31)
    # line 32: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 32, raw: "WHEN init_provider_registry"}, 32)
    # line 33: WHEN register_provider name="deepseek" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "deepseek"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 33, raw: "WHEN register_provider name=\"deepseek\" module=\"MockProvider\""}, 33)
    # line 34: WHEN switch_provider_expect_error name="nonexistent"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :switch_provider_expect_error, %{name: "nonexistent"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 34, raw: "WHEN switch_provider_expect_error name=\"nonexistent\""}, 34)
    # line 35: THEN assert_provider_error contains="not_found"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_error, %{contains: "not_found"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 35, raw: "THEN assert_provider_error contains=\"not_found\""}, 35)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-005
  @tag :provider
  @tag :unit
  test "[PROVIDER-005] 首个注册自动设为当前" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-005"}
    # line 38: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 38, raw: "GIVEN create_temp_dir"}, 38)
    # line 39: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 39, raw: "WHEN init_provider_registry"}, 39)
    # line 40: WHEN register_provider name="first_provider" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "first_provider"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 40, raw: "WHEN register_provider name=\"first_provider\" module=\"MockProvider\""}, 40)
    # line 41: THEN assert_current_provider expected="first_provider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_provider, %{expected: "first_provider"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 41, raw: "THEN assert_current_provider expected=\"first_provider\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-006
  @tag :provider
  @tag :unit
  test "[PROVIDER-006] 降级到下一个 Provider" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-006"}
    # line 48: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 48, raw: "GIVEN create_temp_dir"}, 48)
    # line 49: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 49, raw: "WHEN init_provider_registry"}, 49)
    # line 50: WHEN register_provider name="primary" module="MockProvider" priority=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "primary", priority: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 50, raw: "WHEN register_provider name=\"primary\" module=\"MockProvider\" priority=10"}, 50)
    # line 51: WHEN register_provider name="fallback" module="MockProvider" priority=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "fallback", priority: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 51, raw: "WHEN register_provider name=\"fallback\" module=\"MockProvider\" priority=5"}, 51)
    # line 52: WHEN provider_fallback from="primary"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :provider_fallback, %{from: "primary"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 52, raw: "WHEN provider_fallback from=\"primary\""}, 52)
    # line 53: THEN assert_current_provider expected="fallback"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_current_provider, %{expected: "fallback"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 53, raw: "THEN assert_current_provider expected=\"fallback\""}, 53)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-007
  @tag :provider
  @tag :unit
  test "[PROVIDER-007] 无降级目标返回错误" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-007"}
    # line 56: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 56, raw: "GIVEN create_temp_dir"}, 56)
    # line 57: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 57, raw: "WHEN init_provider_registry"}, 57)
    # line 58: WHEN register_provider name="only_one" module="MockProvider"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "only_one"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 58, raw: "WHEN register_provider name=\"only_one\" module=\"MockProvider\""}, 58)
    # line 59: WHEN provider_fallback_expect_error from="only_one"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :provider_fallback_expect_error, %{from: "only_one"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 59, raw: "WHEN provider_fallback_expect_error from=\"only_one\""}, 59)
    # line 60: THEN assert_provider_error contains="no_fallback"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_error, %{contains: "no_fallback"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 60, raw: "THEN assert_provider_error contains=\"no_fallback\""}, 60)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-008
  @tag :provider
  @tag :unit
  test "[PROVIDER-008] Provider 配置校验失败" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-008"}
    # line 63: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 63, raw: "GIVEN create_temp_dir"}, 63)
    # line 64: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 64, raw: "WHEN init_provider_registry"}, 64)
    # line 65: WHEN register_provider_with_invalid_config name="bad" module="MockProviderWithValidation"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider_with_invalid_config, %{module: "MockProviderWithValidation", name: "bad"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 65, raw: "WHEN register_provider_with_invalid_config name=\"bad\" module=\"MockProviderWithValidation\""}, 65)
    # line 66: THEN assert_provider_error contains="invalid"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_error, %{contains: "invalid"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 66, raw: "THEN assert_provider_error contains=\"invalid\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: PROVIDER-009
  @tag :provider
  @tag :unit
  test "[PROVIDER-009] Provider 列表按优先级排序" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "PROVIDER-009"}
    # line 69: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 69, raw: "GIVEN create_temp_dir"}, 69)
    # line 70: WHEN init_provider_registry
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :init_provider_registry, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 70, raw: "WHEN init_provider_registry"}, 70)
    # line 71: WHEN register_provider name="low" module="MockProvider" priority=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "low", priority: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 71, raw: "WHEN register_provider name=\"low\" module=\"MockProvider\" priority=1"}, 71)
    # line 72: WHEN register_provider name="high" module="MockProvider" priority=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "high", priority: 10}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 72, raw: "WHEN register_provider name=\"high\" module=\"MockProvider\" priority=10"}, 72)
    # line 73: WHEN register_provider name="mid" module="MockProvider" priority=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :register_provider, %{module: "MockProvider", name: "mid", priority: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 73, raw: "WHEN register_provider name=\"mid\" module=\"MockProvider\" priority=5"}, 73)
    # line 74: THEN assert_provider_list_order expected="high,mid,low"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_provider_list_order, %{expected: "high,mid,low"}, %{file: "/home/wangbo/document/gong/docs/bdd/provider.dsl", line: 74, raw: "THEN assert_provider_list_order expected=\"high,mid,low\""}, 74)
    _ctx = ctx
    :ok
  end

end
