# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/session_edge.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.SessionEdgeTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: SESSION-ERR-001
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-001] fork 后父会话内容不变" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 10, raw: "GIVEN tape_init"}, 10)
    # line 11: GIVEN tape_append kind="user" content="msg1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "msg1", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 11, raw: "GIVEN tape_append kind=\"user\" content=\"msg1\""}, 11)
    # line 12: GIVEN tape_append kind="assistant" content="reply1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "reply1", kind: "assistant"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 12, raw: "GIVEN tape_append kind=\"assistant\" content=\"reply1\""}, 12)
    # line 13: GIVEN tape_fork
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_fork, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 13, raw: "GIVEN tape_fork"}, 13)
    # line 14: THEN assert_entry_count expected=2
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 2}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 14, raw: "THEN assert_entry_count expected=2"}, 14)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-ERR-002
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-002] fork 后子会话保留用户消息" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-002"}
    # line 17: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 17, raw: "GIVEN create_temp_dir"}, 17)
    # line 18: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 18, raw: "GIVEN tape_init"}, 18)
    # line 19: GIVEN tape_append kind="user" content="original"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "original", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 19, raw: "GIVEN tape_append kind=\"user\" content=\"original\""}, 19)
    # line 20: GIVEN tape_fork
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_fork, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 20, raw: "GIVEN tape_fork"}, 20)
    # line 21: GIVEN tape_append kind="user" content="forked_msg"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "forked_msg", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 21, raw: "GIVEN tape_append kind=\"user\" content=\"forked_msg\""}, 21)
    # line 22: THEN assert_entry_count expected=2
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 2}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 22, raw: "THEN assert_entry_count expected=2"}, 22)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-ERR-003
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-003] 恢复会话时消息顺序正确" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-003"}
    # line 25: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 25, raw: "GIVEN create_temp_dir"}, 25)
    # line 26: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 26, raw: "GIVEN tape_init"}, 26)
    # line 27: GIVEN tape_append kind="user" content="first"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "first", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 27, raw: "GIVEN tape_append kind=\"user\" content=\"first\""}, 27)
    # line 28: GIVEN tape_append kind="assistant" content="second"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "second", kind: "assistant"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 28, raw: "GIVEN tape_append kind=\"assistant\" content=\"second\""}, 28)
    # line 29: GIVEN tape_append kind="user" content="third"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "third", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 29, raw: "GIVEN tape_append kind=\"user\" content=\"third\""}, 29)
    # line 30: WHEN when_tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :when_tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 30, raw: "WHEN when_tape_init"}, 30)
    # line 31: THEN assert_entry_count expected=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 31, raw: "THEN assert_entry_count expected=3"}, 31)
    # line 32: THEN assert_entry_order sequence="first,second,third"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_order, %{sequence: "first,second,third"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 32, raw: "THEN assert_entry_order sequence=\"first,second,third\""}, 32)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-ERR-004
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-004] 错误/中止消息在会话树中可见" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-004"}
    # line 35: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 35, raw: "GIVEN create_temp_dir"}, 35)
    # line 36: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 36, raw: "GIVEN tape_init"}, 36)
    # line 37: GIVEN tape_append kind="error" content="something went wrong"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "something went wrong", kind: "error"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 37, raw: "GIVEN tape_append kind=\"error\" content=\"something went wrong\""}, 37)
    # line 38: THEN assert_entry_count expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 38, raw: "THEN assert_entry_count expected=1"}, 38)
    # line 39: THEN assert_entry_order sequence="something went wrong"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_order, %{sequence: "something went wrong"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 39, raw: "THEN assert_entry_order sequence=\"something went wrong\""}, 39)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-ERR-005
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-005] 待处理消息在 session 切换时被清理" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-005"}
    # line 46: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 46, raw: "GIVEN create_temp_dir"}, 46)
    # line 47: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 47, raw: "GIVEN tape_init"}, 47)
    # line 48: GIVEN tape_add_pending content="pending message 1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_add_pending, %{content: "pending message 1"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 48, raw: "GIVEN tape_add_pending content=\"pending message 1\""}, 48)
    # line 49: GIVEN tape_add_pending content="pending message 2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_add_pending, %{content: "pending message 2"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 49, raw: "GIVEN tape_add_pending content=\"pending message 2\""}, 49)
    # line 50: WHEN tape_switch_session
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_switch_session, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 50, raw: "WHEN tape_switch_session"}, 50)
    # line 51: THEN assert_pending_cleared
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_pending_cleared, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 51, raw: "THEN assert_pending_cleared"}, 51)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-ERR-006
  @tag :tape
  @tag :unit
  test "[SESSION-ERR-006] 异步事件 handler 错误被正确传播" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-ERR-006"}
    # line 54: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 54, raw: "GIVEN create_temp_dir"}, 54)
    # line 55: GIVEN register_failing_event_handler
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_failing_event_handler, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 55, raw: "GIVEN register_failing_event_handler"}, 55)
    # line 56: WHEN emit_event event="test_event"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :emit_event, %{event: "test_event"}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 56, raw: "WHEN emit_event event=\"test_event\""}, 56)
    # line 57: THEN assert_handler_error_propagated
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_handler_error_propagated, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/session_edge.dsl", line: 57, raw: "THEN assert_handler_error_propagated"}, 57)
    _ctx = ctx
    :ok
  end

end
