# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/settings.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.SettingsTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: SETTINGS-001
  @tag :settings
  @tag :unit
  test "[SETTINGS-001] 无配置文件返回默认值" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SETTINGS-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN init_settings
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_settings, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 10, raw: "GIVEN init_settings"}, 10)
    # line 11: WHEN get_setting key="model"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :get_setting, %{key: "model"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 11, raw: "WHEN get_setting key=\"model\""}, 11)
    # line 12: THEN assert_setting_value expected="deepseek:deepseek-chat"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_setting_value, %{expected: "deepseek:deepseek-chat"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 12, raw: "THEN assert_setting_value expected=\"deepseek:deepseek-chat\""}, 12)
    _ctx = ctx
    :ok
  end

  # Source: SETTINGS-002
  @tag :settings
  @tag :unit
  test "[SETTINGS-002] 项目级覆盖全局" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SETTINGS-002"}
    # line 15: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 15, raw: "GIVEN create_temp_dir"}, 15)
    # line 16: GIVEN create_settings_file scope="project" content="{\"model\": \"openai:gpt-4\"}"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_settings_file, %{content: "{\\\"model\\\": \\\"openai:gpt-4\\\"}", scope: "project"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 16, raw: "GIVEN create_settings_file scope=\"project\" content=\"{\\\"model\\\": \\\"openai:gpt-4\\\"}\""}, 16)
    # line 17: GIVEN init_settings
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_settings, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 17, raw: "GIVEN init_settings"}, 17)
    # line 18: WHEN get_setting key="model"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :get_setting, %{key: "model"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 18, raw: "WHEN get_setting key=\"model\""}, 18)
    # line 19: THEN assert_setting_value expected="openai:gpt-4"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_setting_value, %{expected: "openai:gpt-4"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 19, raw: "THEN assert_setting_value expected=\"openai:gpt-4\""}, 19)
    _ctx = ctx
    :ok
  end

  # Source: SETTINGS-003
  @tag :settings
  @tag :unit
  test "[SETTINGS-003] 运行时修改立即生效" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SETTINGS-003"}
    # line 22: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 22, raw: "GIVEN create_temp_dir"}, 22)
    # line 23: GIVEN init_settings
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :init_settings, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 23, raw: "GIVEN init_settings"}, 23)
    # line 24: WHEN set_setting key="temperature" value="0.5"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :set_setting, %{key: "temperature", value: "0.5"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 24, raw: "WHEN set_setting key=\"temperature\" value=\"0.5\""}, 24)
    # line 25: WHEN get_setting key="temperature"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :get_setting, %{key: "temperature"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 25, raw: "WHEN get_setting key=\"temperature\""}, 25)
    # line 26: THEN assert_setting_value expected="0.5"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_setting_value, %{expected: "0.5"}, %{file: "/home/wangbo/document/gong/docs/bdd/settings.dsl", line: 26, raw: "THEN assert_setting_value expected=\"0.5\""}, 26)
    _ctx = ctx
    :ok
  end

end
