# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/steering.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.SteeringTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-STEER-001
  @tag :agent_loop
  @tag :unit
  test "[BDD-STEER-001] steering 消息入队出队" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-STEER-001"}
    # line 5: GIVEN steering_queue_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :steering_queue_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 5, raw: "GIVEN steering_queue_empty"}, 5)
    # line 6: WHEN steering_push message="中断请求"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :steering_push, %{message: "中断请求"}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 6, raw: "WHEN steering_push message=\"中断请求\""}, 6)
    # line 7: THEN assert_steering_pending
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_pending, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 7, raw: "THEN assert_steering_pending"}, 7)
    # line 8: WHEN steering_check
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :steering_check, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 8, raw: "WHEN steering_check"}, 8)
    # line 9: THEN assert_steering_message contains="中断请求"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_message, %{contains: "中断请求"}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 9, raw: "THEN assert_steering_message contains=\"中断请求\""}, 9)
    # line 10: THEN assert_steering_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 10, raw: "THEN assert_steering_empty"}, 10)
    _ctx = ctx
    :ok
  end

  # Source: BDD-STEER-002
  @tag :agent_loop
  @tag :unit
  test "[BDD-STEER-002] steering 跳过结果格式" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-STEER-002"}
    # line 13: GIVEN steering_queue_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :steering_queue_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 13, raw: "GIVEN steering_queue_empty"}, 13)
    # line 14: WHEN steering_skip_result tool="bash"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :steering_skip_result, %{tool: "bash"}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 14, raw: "WHEN steering_skip_result tool=\"bash\""}, 14)
    # line 15: THEN assert_steering_skip_contains text="Skipped"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_skip_contains, %{text: "Skipped"}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 15, raw: "THEN assert_steering_skip_contains text=\"Skipped\""}, 15)
    # line 16: THEN assert_steering_skip_contains text="bash"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_steering_skip_contains, %{text: "bash"}, %{file: "/home/wangbo/document/gong/docs/bdd/steering.dsl", line: 16, raw: "THEN assert_steering_skip_contains text=\"bash\""}, 16)
    _ctx = ctx
    :ok
  end

end
