# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/stream_integration.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.StreamIntegrationTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: STREAM-001
  @tag :integration
  @tag :stream
  test "[STREAM-001] 纯文本流式" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 10, raw: "GIVEN configure_agent"}, 10)
    # line 11: GIVEN mock_stream_response chunks="chunk:你好|chunk:世界|chunk:！|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:你好|chunk:世界|chunk:！|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 11, raw: "GIVEN mock_stream_response chunks=\"chunk:你好|chunk:世界|chunk:！|done\""}, 11)
    # line 12: WHEN agent_stream prompt="测试流式"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "测试流式"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 12, raw: "WHEN agent_stream prompt=\"测试流式\""}, 12)
    # line 13: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 13, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 13)
    # line 14: THEN assert_stream_content expected="你好世界！"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_content, %{expected: "你好世界！"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 14, raw: "THEN assert_stream_content expected=\"你好世界！\""}, 14)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-002
  @tag :integration
  @tag :stream
  test "[STREAM-002]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-002"}
    # line 17: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 17, raw: "GIVEN create_temp_dir"}, 17)
    # line 18: GIVEN create_temp_file path="stream.txt" content="tool_stream_test"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "tool_stream_test", path: "stream.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 18, raw: "GIVEN create_temp_file path=\"stream.txt\" content=\"tool_stream_test\""}, 18)
    # line 19: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 19, raw: "GIVEN configure_agent"}, 19)
    # line 20: GIVEN mock_llm_response response_type="tool_call" tool="read_file" tool_args="file_path={{workspace}}/stream.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "read_file", tool_args: "file_path={{workspace}}/stream.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 20, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"read_file\" tool_args=\"file_path={{workspace}}/stream.txt\""}, 20)
    # line 21: GIVEN mock_llm_response response_type="text" content="流式工具调用完成"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "流式工具调用完成", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 21, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"流式工具调用完成\""}, 21)
    # line 22: WHEN agent_stream prompt="流式读文件"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "流式读文件"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 22, raw: "WHEN agent_stream prompt=\"流式读文件\""}, 22)
    # line 23: THEN assert_tool_was_called tool="read_file"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_was_called, %{tool: "read_file"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 23, raw: "THEN assert_tool_was_called tool=\"read_file\""}, 23)
    # line 24: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 24, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 24)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-003
  @tag :integration
  @tag :stream
  test "[STREAM-003] 流式中断有内容" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-003"}
    # line 27: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 27, raw: "GIVEN create_temp_dir"}, 27)
    # line 28: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 28, raw: "GIVEN configure_agent"}, 28)
    # line 29: GIVEN mock_stream_response chunks="chunk:已收到|abort:用户中断"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:已收到|abort:用户中断"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 29, raw: "GIVEN mock_stream_response chunks=\"chunk:已收到|abort:用户中断\""}, 29)
    # line 30: WHEN agent_stream prompt="测试中断"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "测试中断"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 30, raw: "WHEN agent_stream prompt=\"测试中断\""}, 30)
    # line 31: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 31, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 31)
    # line 32: THEN assert_stream_content expected="已收到"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_content, %{expected: "已收到"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 32, raw: "THEN assert_stream_content expected=\"已收到\""}, 32)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-004
  @tag :integration
  @tag :stream
  test "[STREAM-004] 空内容中断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-004"}
    # line 35: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 35, raw: "GIVEN create_temp_dir"}, 35)
    # line 36: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 36, raw: "GIVEN configure_agent"}, 36)
    # line 37: GIVEN mock_stream_response chunks="abort:立即中断"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "abort:立即中断"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 37, raw: "GIVEN mock_stream_response chunks=\"abort:立即中断\""}, 37)
    # line 38: WHEN agent_stream prompt="测试空中断"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "测试空中断"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 38, raw: "WHEN agent_stream prompt=\"测试空中断\""}, 38)
    # line 39: THEN assert_no_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 39, raw: "THEN assert_no_crash"}, 39)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-005
  @tag :integration
  @tag :stream
  test "[STREAM-005] 事件序列正确" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-005"}
    # line 42: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 42, raw: "GIVEN create_temp_dir"}, 42)
    # line 43: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 43, raw: "GIVEN configure_agent"}, 43)
    # line 44: GIVEN mock_stream_response chunks="chunk:A|chunk:B|chunk:C|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:A|chunk:B|chunk:C|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 44, raw: "GIVEN mock_stream_response chunks=\"chunk:A|chunk:B|chunk:C|done\""}, 44)
    # line 45: WHEN agent_stream prompt="序列测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "序列测试"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 45, raw: "WHEN agent_stream prompt=\"序列测试\""}, 45)
    # line 46: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 46, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-006
  @tag :integration
  @tag :stream
  test "[STREAM-006] 流式加 Hook" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-006"}
    # line 49: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 49, raw: "GIVEN create_temp_dir"}, 49)
    # line 50: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 50, raw: "GIVEN configure_agent"}, 50)
    # line 51: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 51, raw: "GIVEN register_hook module=\"AllowAll\""}, 51)
    # line 52: GIVEN mock_llm_response response_type="text" content="Hook流式测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "Hook流式测试", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 52, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"Hook流式测试\""}, 52)
    # line 53: WHEN agent_stream prompt="流式Hook"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "流式Hook"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 53, raw: "WHEN agent_stream prompt=\"流式Hook\""}, 53)
    # line 54: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 54, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 54)
    # line 55: THEN assert_agent_reply contains="Hook流式测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "Hook流式测试"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 55, raw: "THEN assert_agent_reply contains=\"Hook流式测试\""}, 55)
    # line 56: THEN assert_no_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 56, raw: "THEN assert_no_crash"}, 56)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-007
  @tag :integration
  @tag :stream
  test "[STREAM-007] 流式超时" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-007"}
    # line 59: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 59, raw: "GIVEN create_temp_dir"}, 59)
    # line 60: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 60, raw: "GIVEN configure_agent"}, 60)
    # line 61: GIVEN mock_stream_response chunks="chunk:开始|delay:6000|chunk:超时|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:开始|delay:6000|chunk:超时|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 61, raw: "GIVEN mock_stream_response chunks=\"chunk:开始|delay:6000|chunk:超时|done\""}, 61)
    # line 62: WHEN agent_stream prompt="超时测试"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "超时测试"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 62, raw: "WHEN agent_stream prompt=\"超时测试\""}, 62)
    # line 63: THEN assert_no_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 63, raw: "THEN assert_no_crash"}, 63)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-008
  @tag :e2e
  @tag :integration
  @tag :stream
  test "[STREAM-008] E2E 真实流" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-008"}
    # line 66: GIVEN check_e2e_provider
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :check_e2e_provider, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 66, raw: "GIVEN check_e2e_provider"}, 66)
    # line 67: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 67, raw: "GIVEN create_temp_dir"}, 67)
    # line 68: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 68, raw: "GIVEN configure_agent"}, 68)
    # line 69: WHEN agent_stream prompt="1加1等于几？只回答数字"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "1加1等于几？只回答数字"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 69, raw: "WHEN agent_stream prompt=\"1加1等于几？只回答数字\""}, 69)
    # line 70: THEN assert_stream_events sequence="start,delta,end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_events, %{sequence: "start,delta,end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 70, raw: "THEN assert_stream_events sequence=\"start,delta,end\""}, 70)
    # line 71: THEN assert_agent_reply contains="2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "2"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 71, raw: "THEN assert_agent_reply contains=\"2\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-009
  @tag :integration
  @tag :stream
  test "[STREAM-009] 多 chunk 拼接边界" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-009"}
    # line 78: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 78, raw: "GIVEN create_temp_dir"}, 78)
    # line 79: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 79, raw: "GIVEN configure_agent"}, 79)
    # line 80: GIVEN mock_stream_response chunks="chunk:a|chunk:b|chunk:c|chunk:d|chunk:e|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:a|chunk:b|chunk:c|chunk:d|chunk:e|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 80, raw: "GIVEN mock_stream_response chunks=\"chunk:a|chunk:b|chunk:c|chunk:d|chunk:e|done\""}, 80)
    # line 81: WHEN agent_stream prompt="多chunk拼接"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "多chunk拼接"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 81, raw: "WHEN agent_stream prompt=\"多chunk拼接\""}, 81)
    # line 82: THEN assert_stream_content expected="abcde"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_content, %{expected: "abcde"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 82, raw: "THEN assert_stream_content expected=\"abcde\""}, 82)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-010
  @tag :integration
  @tag :stream
  test "[STREAM-010] 单字符 chunk 流" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-010"}
    # line 85: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 85, raw: "GIVEN create_temp_dir"}, 85)
    # line 86: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 86, raw: "GIVEN configure_agent"}, 86)
    # line 87: GIVEN mock_stream_response chunks="chunk:H|chunk:i|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:H|chunk:i|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 87, raw: "GIVEN mock_stream_response chunks=\"chunk:H|chunk:i|done\""}, 87)
    # line 88: WHEN agent_stream prompt="单字符"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "单字符"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 88, raw: "WHEN agent_stream prompt=\"单字符\""}, 88)
    # line 89: THEN assert_stream_content expected="Hi"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_content, %{expected: "Hi"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 89, raw: "THEN assert_stream_content expected=\"Hi\""}, 89)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-011
  @tag :integration
  @tag :stream
  test "[STREAM-011] Unicode chunk 流" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-011"}
    # line 92: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 92, raw: "GIVEN create_temp_dir"}, 92)
    # line 93: GIVEN configure_agent
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 93, raw: "GIVEN configure_agent"}, 93)
    # line 94: GIVEN mock_stream_response chunks="chunk:你|chunk:好|chunk:世|chunk:界|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_stream_response, %{chunks: "chunk:你|chunk:好|chunk:世|chunk:界|done"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 94, raw: "GIVEN mock_stream_response chunks=\"chunk:你|chunk:好|chunk:世|chunk:界|done\""}, 94)
    # line 95: WHEN agent_stream prompt="Unicode流"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_stream, %{prompt: "Unicode流"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 95, raw: "WHEN agent_stream prompt=\"Unicode流\""}, 95)
    # line 96: THEN assert_stream_content expected="你好世界"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_stream_content, %{expected: "你好世界"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 96, raw: "THEN assert_stream_content expected=\"你好世界\""}, 96)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-012
  @tag :stream
  @tag :unit
  test "[STREAM-012] tool_chunks_to_events 事件序列" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-012"}
    # line 103: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 103, raw: "GIVEN create_temp_dir"}, 103)
    # line 104: WHEN stream_tool_chunks tool_name="read_file" chunks="chunk:{\"path\":\"/tmp\"}|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :stream_tool_chunks, %{chunks: "chunk:{\\\"path\\\":\\\"/tmp\\\"}|done", tool_name: "read_file"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 104, raw: "WHEN stream_tool_chunks tool_name=\"read_file\" chunks=\"chunk:{\\\"path\\\":\\\"/tmp\\\"}|done\""}, 104)
    # line 105: THEN assert_tool_event_sequence sequence="tool_start,tool_delta,tool_end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_event_sequence, %{sequence: "tool_start,tool_delta,tool_end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 105, raw: "THEN assert_tool_event_sequence sequence=\"tool_start,tool_delta,tool_end\""}, 105)
    _ctx = ctx
    :ok
  end

  # Source: STREAM-013
  @tag :stream
  @tag :unit
  test "[STREAM-013] tool 事件包含工具名" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "STREAM-013"}
    # line 108: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 108, raw: "GIVEN create_temp_dir"}, 108)
    # line 109: WHEN stream_tool_chunks tool_name="bash" chunks="chunk:ls -la|done"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :stream_tool_chunks, %{chunks: "chunk:ls -la|done", tool_name: "bash"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 109, raw: "WHEN stream_tool_chunks tool_name=\"bash\" chunks=\"chunk:ls -la|done\""}, 109)
    # line 110: THEN assert_tool_event_sequence sequence="tool_start,tool_delta,tool_end"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_event_sequence, %{sequence: "tool_start,tool_delta,tool_end"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 110, raw: "THEN assert_tool_event_sequence sequence=\"tool_start,tool_delta,tool_end\""}, 110)
    # line 111: THEN assert_tool_event_name expected="bash"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_event_name, %{expected: "bash"}, %{file: "/home/wangbo/document/gong/docs/bdd/stream_integration.dsl", line: 111, raw: "THEN assert_tool_event_name expected=\"bash\""}, 111)
    _ctx = ctx
    :ok
  end

end
