# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/tape_session.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.TapeSessionTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: SESSION-001
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-001] 从中间分支" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 10, raw: "GIVEN tape_init"}, 10)
    # line 11: GIVEN tape_append kind="user" content="第一条消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "第一条消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 11, raw: "GIVEN tape_append kind=\"user\" content=\"第一条消息\""}, 11)
    # line 12: GIVEN tape_handoff name="phase-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "phase-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 12, raw: "GIVEN tape_handoff name=\"phase-1\""}, 12)
    # line 13: GIVEN tape_append anchor="phase-1" kind="user" content="第二条消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "phase-1", content: "第二条消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 13, raw: "GIVEN tape_append anchor=\"phase-1\" kind=\"user\" content=\"第二条消息\""}, 13)
    # line 14: GIVEN tape_handoff name="phase-2"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "phase-2"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 14, raw: "GIVEN tape_handoff name=\"phase-2\""}, 14)
    # line 15: GIVEN tape_append anchor="phase-2" kind="user" content="第三条消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "phase-2", content: "第三条消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 15, raw: "GIVEN tape_append anchor=\"phase-2\" kind=\"user\" content=\"第三条消息\""}, 15)
    # line 16: WHEN tape_branch_from anchor="phase-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "phase-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 16, raw: "WHEN tape_branch_from anchor=\"phase-1\""}, 16)
    # line 17: THEN assert_tape_branches anchor="phase-1" expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tape_branches, %{anchor: "phase-1", expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 17, raw: "THEN assert_tape_branches anchor=\"phase-1\" expected=1"}, 17)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-002
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-002] 分支导航" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-002"}
    # line 20: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 20, raw: "GIVEN create_temp_dir"}, 20)
    # line 21: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 21, raw: "GIVEN tape_init"}, 21)
    # line 22: GIVEN tape_append kind="user" content="根消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "根消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 22, raw: "GIVEN tape_append kind=\"user\" content=\"根消息\""}, 22)
    # line 23: GIVEN tape_handoff name="branch-a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "branch-a"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 23, raw: "GIVEN tape_handoff name=\"branch-a\""}, 23)
    # line 24: GIVEN tape_append anchor="branch-a" kind="user" content="分支A消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "branch-a", content: "分支A消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 24, raw: "GIVEN tape_append anchor=\"branch-a\" kind=\"user\" content=\"分支A消息\""}, 24)
    # line 25: WHEN tape_branch_from anchor="session-start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "session-start"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 25, raw: "WHEN tape_branch_from anchor=\"session-start\""}, 25)
    # line 26: WHEN tape_navigate anchor="branch-a"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_navigate, %{anchor: "branch-a"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 26, raw: "WHEN tape_navigate anchor=\"branch-a\""}, 26)
    # line 27: THEN assert_entry_count expected=2
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 2}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 27, raw: "THEN assert_entry_count expected=2"}, 27)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-003
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-003] 分支上下文" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-003"}
    # line 30: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 30, raw: "GIVEN create_temp_dir"}, 30)
    # line 31: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 31, raw: "GIVEN tape_init"}, 31)
    # line 32: GIVEN tape_append kind="user" content="根内容"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "根内容", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 32, raw: "GIVEN tape_append kind=\"user\" content=\"根内容\""}, 32)
    # line 33: GIVEN tape_handoff name="child-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "child-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 33, raw: "GIVEN tape_handoff name=\"child-1\""}, 33)
    # line 34: GIVEN tape_append anchor="child-1" kind="user" content="子内容"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "child-1", content: "子内容", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 34, raw: "GIVEN tape_append anchor=\"child-1\" kind=\"user\" content=\"子内容\""}, 34)
    # line 35: WHEN tape_build_context anchor="child-1"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_build_context, %{anchor: "child-1"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 35, raw: "WHEN tape_build_context anchor=\"child-1\""}, 35)
    # line 36: THEN assert_tape_context_path count=1 contains="子内容"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tape_context_path, %{contains: "子内容", count: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 36, raw: "THEN assert_tape_context_path count=1 contains=\"子内容\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-004
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-004] 深度分支" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-004"}
    # line 39: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 39, raw: "GIVEN create_temp_dir"}, 39)
    # line 40: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 40, raw: "GIVEN tape_init"}, 40)
    # line 41: GIVEN tape_append kind="user" content="level-0"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "level-0", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 41, raw: "GIVEN tape_append kind=\"user\" content=\"level-0\""}, 41)
    # line 42: WHEN tape_branch_from anchor="session-start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "session-start"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 42, raw: "WHEN tape_branch_from anchor=\"session-start\""}, 42)
    # line 43: THEN assert_tape_branches anchor="session-start" expected=1
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tape_branches, %{anchor: "session-start", expected: 1}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 43, raw: "THEN assert_tape_branches anchor=\"session-start\" expected=1"}, 43)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-005
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-005] 分支后追加" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-005"}
    # line 46: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 46, raw: "GIVEN create_temp_dir"}, 46)
    # line 47: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 47, raw: "GIVEN tape_init"}, 47)
    # line 48: GIVEN tape_append kind="user" content="原始消息"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "原始消息", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 48, raw: "GIVEN tape_append kind=\"user\" content=\"原始消息\""}, 48)
    # line 49: GIVEN tape_handoff name="original-path"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_handoff, %{name: "original-path"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 49, raw: "GIVEN tape_handoff name=\"original-path\""}, 49)
    # line 50: GIVEN tape_append anchor="original-path" kind="user" content="原始路径"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "original-path", content: "原始路径", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 50, raw: "GIVEN tape_append anchor=\"original-path\" kind=\"user\" content=\"原始路径\""}, 50)
    # line 51: WHEN tape_branch_from anchor="session-start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "session-start"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 51, raw: "WHEN tape_branch_from anchor=\"session-start\""}, 51)
    # line 52: GIVEN tape_append anchor="original-path" kind="user" content="原路径新增"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{anchor: "original-path", content: "原路径新增", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 52, raw: "GIVEN tape_append anchor=\"original-path\" kind=\"user\" content=\"原路径新增\""}, 52)
    # line 53: THEN assert_entry_count expected=3
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_entry_count, %{expected: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 53, raw: "THEN assert_entry_count expected=3"}, 53)
    _ctx = ctx
    :ok
  end

  # Source: SESSION-006
  @tag :session
  @tag :tape
  @tag :unit
  test "[SESSION-006] 分支列表" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "SESSION-006"}
    # line 56: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 56, raw: "GIVEN create_temp_dir"}, 56)
    # line 57: GIVEN tape_init
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_init, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 57, raw: "GIVEN tape_init"}, 57)
    # line 58: GIVEN tape_append kind="user" content="根"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :tape_append, %{content: "根", kind: "user"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 58, raw: "GIVEN tape_append kind=\"user\" content=\"根\""}, 58)
    # line 59: WHEN tape_branch_from anchor="session-start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "session-start"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 59, raw: "WHEN tape_branch_from anchor=\"session-start\""}, 59)
    # line 60: WHEN tape_branch_from anchor="session-start"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tape_branch_from, %{anchor: "session-start"}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 60, raw: "WHEN tape_branch_from anchor=\"session-start\""}, 60)
    # line 61: THEN assert_tape_branches anchor="session-start" expected=2
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tape_branches, %{anchor: "session-start", expected: 2}, %{file: "/home/wangbo/document/gong/docs/bdd/tape_session.dsl", line: 61, raw: "THEN assert_tape_branches anchor=\"session-start\" expected=2"}, 61)
    _ctx = ctx
    :ok
  end

end
