# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/thinking.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ThinkingTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: THINKING-001
  @tag :thinking
  @tag :unit
  test "[THINKING-001] 有效 level 验证" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "THINKING-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: WHEN validate_thinking_level level="high"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :validate_thinking_level, %{level: "high"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 10, raw: "WHEN validate_thinking_level level=\"high\""}, 10)
    # line 11: THEN assert_thinking_valid
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_thinking_valid, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 11, raw: "THEN assert_thinking_valid"}, 11)
    _ctx = ctx
    :ok
  end

  # Source: THINKING-002
  @tag :thinking
  @tag :unit
  test "[THINKING-002] 无效 level 拒绝" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "THINKING-002"}
    # line 14: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 14, raw: "GIVEN create_temp_dir"}, 14)
    # line 15: WHEN validate_thinking_level level="超高"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :validate_thinking_level, %{level: "超高"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 15, raw: "WHEN validate_thinking_level level=\"超高\""}, 15)
    # line 16: THEN assert_thinking_invalid
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_thinking_invalid, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 16, raw: "THEN assert_thinking_invalid"}, 16)
    _ctx = ctx
    :ok
  end

  # Source: THINKING-003
  @tag :thinking
  @tag :unit
  test "[THINKING-003] Level 对应 token 预算" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "THINKING-003"}
    # line 19: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 19, raw: "GIVEN create_temp_dir"}, 19)
    # line 20: WHEN get_thinking_budget level="high"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :get_thinking_budget, %{level: "high"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 20, raw: "WHEN get_thinking_budget level=\"high\""}, 20)
    # line 21: THEN assert_thinking_budget expected=8192
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_thinking_budget, %{expected: 8192}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 21, raw: "THEN assert_thinking_budget expected=8192"}, 21)
    _ctx = ctx
    :ok
  end

  # Source: THINKING-004
  @tag :thinking
  @tag :unit
  test "[THINKING-004] Anthropic provider 参数转换" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "THINKING-004"}
    # line 24: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 24, raw: "GIVEN create_temp_dir"}, 24)
    # line 25: WHEN thinking_to_provider level="high" provider="anthropic"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :thinking_to_provider, %{level: "high", provider: "anthropic"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 25, raw: "WHEN thinking_to_provider level=\"high\" provider=\"anthropic\""}, 25)
    # line 26: THEN assert_thinking_params contains="budget_tokens"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_thinking_params, %{contains: "budget_tokens"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 26, raw: "THEN assert_thinking_params contains=\"budget_tokens\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: THINKING-005
  @tag :thinking
  @tag :unit
  test "[THINKING-005] off level 返回空参数" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "THINKING-005"}
    # line 29: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 29, raw: "GIVEN create_temp_dir"}, 29)
    # line 30: WHEN thinking_to_provider level="off" provider="anthropic"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :thinking_to_provider, %{level: "off", provider: "anthropic"}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 30, raw: "WHEN thinking_to_provider level=\"off\" provider=\"anthropic\""}, 30)
    # line 31: THEN assert_thinking_params_empty
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_thinking_params_empty, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/thinking.dsl", line: 31, raw: "THEN assert_thinking_params_empty"}, 31)
    _ctx = ctx
    :ok
  end

end
