# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/tool_edge.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.ToolEdgeTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: TOOL-EDGE-001
  @tag :external_io
  @tag :unit
  test "[TOOL-EDGE-001] 工具参数为 nil/空 map 时返回合理错误" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-001"}
    # line 9: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 9, raw: "GIVEN create_temp_dir"}, 9)
    # line 10: WHEN tool_dispatch_nil_params tool_name="read_file"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_dispatch_nil_params, %{tool_name: "read_file"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 10, raw: "WHEN tool_dispatch_nil_params tool_name=\"read_file\""}, 10)
    # line 11: THEN assert_tool_error error_contains="参数"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error, %{error_contains: "参数"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 11, raw: "THEN assert_tool_error error_contains=\"参数\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-005
  @tag :external_io
  @tag :unit
  test "[TOOL-EDGE-005]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-005"}
    # line 14: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 14, raw: "GIVEN create_temp_dir"}, 14)
    # line 15: WHEN tool_read path="/nonexistent_file_xyz.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_read, %{path: "/nonexistent_file_xyz.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 15, raw: "WHEN tool_read path=\"/nonexistent_file_xyz.txt\""}, 15)
    # line 16: THEN assert_tool_error error_contains="ENOENT"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error, %{error_contains: "ENOENT"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 16, raw: "THEN assert_tool_error error_contains=\"ENOENT\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-002
  @tag :agent
  @tag :integration
  test "[TOOL-EDGE-002] 工具名大小写不敏感匹配" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-002"}
    # line 23: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 23, raw: "GIVEN create_temp_dir"}, 23)
    # line 24: GIVEN create_temp_file path="case_test.txt" content="case insensitive"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "case insensitive", path: "case_test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 24, raw: "GIVEN create_temp_file path=\"case_test.txt\" content=\"case insensitive\""}, 24)
    # line 25: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 25, raw: "GIVEN configure_agent model=\"mock\""}, 25)
    # line 26: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 26, raw: "GIVEN register_hook module=\"AllowAll\""}, 26)
    # line 27: GIVEN mock_llm_response response_type="tool_call" tool="Read_File" tool_args="file_path={{workspace}}/case_test.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "Read_File", tool_args: "file_path={{workspace}}/case_test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 27, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"Read_File\" tool_args=\"file_path={{workspace}}/case_test.txt\""}, 27)
    # line 28: GIVEN mock_llm_response response_type="text" content="读取成功"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "读取成功", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 28, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"读取成功\""}, 28)
    # line 29: WHEN agent_chat prompt="读文件"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "读文件"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 29, raw: "WHEN agent_chat prompt=\"读文件\""}, 29)
    # line 30: THEN assert_agent_reply contains="读取成功"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "读取成功"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 30, raw: "THEN assert_agent_reply contains=\"读取成功\""}, 30)
    # line 31: THEN assert_no_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 31, raw: "THEN assert_no_crash"}, 31)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-003
  @tag :agent
  @tag :integration
  test "[TOOL-EDGE-003] 工具调用 ID 含特殊字符正常处理" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-003"}
    # line 34: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 34, raw: "GIVEN create_temp_dir"}, 34)
    # line 35: GIVEN create_temp_file path="id_test.txt" content="special id"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_file, %{content: "special id", path: "id_test.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 35, raw: "GIVEN create_temp_file path=\"id_test.txt\" content=\"special id\""}, 35)
    # line 36: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 36, raw: "GIVEN configure_agent model=\"mock\""}, 36)
    # line 37: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 37, raw: "GIVEN register_hook module=\"AllowAll\""}, 37)
    # line 38: GIVEN mock_llm_response response_type="tool_call" tool="read_file" tool_args="file_path={{workspace}}/id_test.txt" tool_id="call:id/with-special_chars.123"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "read_file", tool_args: "file_path={{workspace}}/id_test.txt", tool_id: "call:id/with-special_chars.123"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 38, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"read_file\" tool_args=\"file_path={{workspace}}/id_test.txt\" tool_id=\"call:id/with-special_chars.123\""}, 38)
    # line 39: GIVEN mock_llm_response response_type="text" content="id正常"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "id正常", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 39, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"id正常\""}, 39)
    # line 40: WHEN agent_chat prompt="test"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "test"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 40, raw: "WHEN agent_chat prompt=\"test\""}, 40)
    # line 41: THEN assert_agent_reply contains="id正常"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "id正常"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 41, raw: "THEN assert_agent_reply contains=\"id正常\""}, 41)
    # line 42: THEN assert_no_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 42, raw: "THEN assert_no_crash"}, 42)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-004
  @tag :agent
  @tag :integration
  test "[TOOL-EDGE-004] 孤儿 tool_result 不导致循环崩溃" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-004"}
    # line 45: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 45, raw: "GIVEN create_temp_dir"}, 45)
    # line 46: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 46, raw: "GIVEN configure_agent model=\"mock\""}, 46)
    # line 47: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 47, raw: "GIVEN register_hook module=\"AllowAll\""}, 47)
    # line 48: GIVEN mock_orphan_tool_result
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_orphan_tool_result, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 48, raw: "GIVEN mock_orphan_tool_result"}, 48)
    # line 49: GIVEN mock_llm_response response_type="text" content="已恢复"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "已恢复", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 49, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"已恢复\""}, 49)
    # line 50: WHEN agent_chat_with_orphan prompt="handle orphan"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat_with_orphan, %{prompt: "handle orphan"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 50, raw: "WHEN agent_chat_with_orphan prompt=\"handle orphan\""}, 50)
    # line 51: THEN assert_no_loop_crash
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_no_loop_crash, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 51, raw: "THEN assert_no_loop_crash"}, 51)
    # line 52: THEN assert_agent_reply contains="已恢复"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_agent_reply, %{contains: "已恢复"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 52, raw: "THEN assert_agent_reply contains=\"已恢复\""}, 52)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-006
  @tag :agent
  @tag :integration
  test "[TOOL-EDGE-006] 错误消息包含可操作提示" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-006"}
    # line 59: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 59, raw: "GIVEN create_temp_dir"}, 59)
    # line 60: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 60, raw: "GIVEN configure_agent model=\"mock\""}, 60)
    # line 61: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 61, raw: "GIVEN register_hook module=\"AllowAll\""}, 61)
    # line 62: GIVEN mock_llm_response response_type="tool_call" tool="nonexistent_tool_xyz" tool_args="param=value"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{response_type: "tool_call", tool: "nonexistent_tool_xyz", tool_args: "param=value"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 62, raw: "GIVEN mock_llm_response response_type=\"tool_call\" tool=\"nonexistent_tool_xyz\" tool_args=\"param=value\""}, 62)
    # line 63: GIVEN mock_llm_response response_type="text" content="工具不存在"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "工具不存在", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 63, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"工具不存在\""}, 63)
    # line 64: WHEN agent_chat prompt="use tool"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "use tool"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 64, raw: "WHEN agent_chat prompt=\"use tool\""}, 64)
    # line 65: THEN assert_tool_error_has_available_tools
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_tool_error_has_available_tools, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 65, raw: "THEN assert_tool_error_has_available_tools"}, 65)
    _ctx = ctx
    :ok
  end

  # Source: TOOL-EDGE-007
  @tag :agent
  @tag :integration
  test "[TOOL-EDGE-007] 空 content assistant 消息被过滤" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "TOOL-EDGE-007"}
    # line 68: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 68, raw: "GIVEN create_temp_dir"}, 68)
    # line 69: GIVEN configure_agent model="mock"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :configure_agent, %{model: "mock"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 69, raw: "GIVEN configure_agent model=\"mock\""}, 69)
    # line 70: GIVEN register_hook module="AllowAll"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :register_hook, %{module: "AllowAll"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 70, raw: "GIVEN register_hook module=\"AllowAll\""}, 70)
    # line 71: GIVEN mock_llm_response response_type="text" content=""
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 71, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"\""}, 71)
    # line 72: GIVEN mock_llm_response response_type="text" content="真正回复"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :mock_llm_response, %{content: "真正回复", response_type: "text"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 72, raw: "GIVEN mock_llm_response response_type=\"text\" content=\"真正回复\""}, 72)
    # line 73: WHEN agent_chat prompt="say nothing"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :agent_chat, %{prompt: "say nothing"}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 73, raw: "WHEN agent_chat prompt=\"say nothing\""}, 73)
    # line 74: THEN assert_empty_content_filtered
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_empty_content_filtered, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/tool_edge.dsl", line: 74, raw: "THEN assert_empty_content_filtered"}, 74)
    _ctx = ctx
    :ok
  end

end
