# Generated by bdd_compiler from /home/wangbo/document/gong/docs/bdd/truncate_system.dsl. DO NOT EDIT.

defmodule Gong.BDD.Generated.TruncateSystemTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-TRC-001
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-001] head 空字符串不截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-001"}
    # line 7: GIVEN set_var name="content" value=""
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: ""}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 7, raw: "GIVEN set_var name=\"content\" value=\"\""}, 7)
    # line 8: WHEN truncate_head content_var="content" max_bytes=1000
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_head, %{content_var: "content", max_bytes: 1000}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 8, raw: "WHEN truncate_head content_var=\"content\" max_bytes=1000"}, 8)
    # line 9: THEN assert_truncation_result truncated=false
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: false}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 9, raw: "THEN assert_truncation_result truncated=false"}, 9)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-002
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-002] head 小文本不截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-002"}
    # line 12: GIVEN set_var name="content" value="hello\nworld"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: "hello\\nworld"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 12, raw: "GIVEN set_var name=\"content\" value=\"hello\\nworld\""}, 12)
    # line 13: WHEN truncate_head content_var="content" max_bytes=1000 max_lines=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_head, %{content_var: "content", max_bytes: 1000, max_lines: 100}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 13, raw: "WHEN truncate_head content_var=\"content\" max_bytes=1000 max_lines=100"}, 13)
    # line 14: THEN assert_truncation_result truncated=false
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: false}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 14, raw: "THEN assert_truncation_result truncated=false"}, 14)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-003
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-003] head 超字节限制截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-003"}
    # line 17: GIVEN generate_content name="content" lines=10 line_length=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 100, lines: 10, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 17, raw: "GIVEN generate_content name=\"content\" lines=10 line_length=100"}, 17)
    # line 18: WHEN truncate_head content_var="content" max_bytes=200
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_head, %{content_var: "content", max_bytes: 200}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 18, raw: "WHEN truncate_head content_var=\"content\" max_bytes=200"}, 18)
    # line 19: THEN assert_truncation_result truncated=true truncated_by="bytes"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: true, truncated_by: "bytes"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 19, raw: "THEN assert_truncation_result truncated=true truncated_by=\"bytes\""}, 19)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-004
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-004] head 超行数限制截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-004"}
    # line 22: GIVEN generate_content name="content" lines=100 line_length=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 10, lines: 100, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 22, raw: "GIVEN generate_content name=\"content\" lines=100 line_length=10"}, 22)
    # line 23: WHEN truncate_head content_var="content" max_lines=5 max_bytes=100000
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_head, %{content_var: "content", max_bytes: 100000, max_lines: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 23, raw: "WHEN truncate_head content_var=\"content\" max_lines=5 max_bytes=100000"}, 23)
    # line 24: THEN assert_truncation_result truncated=true truncated_by="lines" output_lines=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{output_lines: 5, truncated: true, truncated_by: "lines"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 24, raw: "THEN assert_truncation_result truncated=true truncated_by=\"lines\" output_lines=5"}, 24)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-005
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-005] head 首行超限" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-005"}
    # line 27: GIVEN generate_content name="content" lines=1 line_length=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 500, lines: 1, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 27, raw: "GIVEN generate_content name=\"content\" lines=1 line_length=500"}, 27)
    # line 28: WHEN truncate_head content_var="content" max_bytes=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_head, %{content_var: "content", max_bytes: 100}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 28, raw: "WHEN truncate_head content_var=\"content\" max_bytes=100"}, 28)
    # line 29: THEN assert_truncation_result truncated=true truncated_by="bytes" first_line_exceeds_limit=true
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{first_line_exceeds_limit: true, truncated: true, truncated_by: "bytes"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 29, raw: "THEN assert_truncation_result truncated=true truncated_by=\"bytes\" first_line_exceeds_limit=true"}, 29)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-006
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-006] tail 恰好在限制值不截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-006"}
    # line 34: GIVEN set_var name="content" value="aaa\nbbb\nccc"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: "aaa\\nbbb\\nccc"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 34, raw: "GIVEN set_var name=\"content\" value=\"aaa\\nbbb\\nccc\""}, 34)
    # line 35: WHEN truncate_tail content_var="content" max_lines=3 max_bytes=11
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_tail, %{content_var: "content", max_bytes: 11, max_lines: 3}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 35, raw: "WHEN truncate_tail content_var=\"content\" max_lines=3 max_bytes=11"}, 35)
    # line 36: THEN assert_truncation_result truncated=false
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: false}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 36, raw: "THEN assert_truncation_result truncated=false"}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-007
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-007] tail 小文本不截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-007"}
    # line 39: GIVEN set_var name="content" value="hello\nworld"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: "hello\\nworld"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 39, raw: "GIVEN set_var name=\"content\" value=\"hello\\nworld\""}, 39)
    # line 40: WHEN truncate_tail content_var="content" max_bytes=1000 max_lines=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_tail, %{content_var: "content", max_bytes: 1000, max_lines: 100}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 40, raw: "WHEN truncate_tail content_var=\"content\" max_bytes=1000 max_lines=100"}, 40)
    # line 41: THEN assert_truncation_result truncated=false
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: false}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 41, raw: "THEN assert_truncation_result truncated=false"}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-008
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-008] tail 超字节限制截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-008"}
    # line 44: GIVEN generate_content name="content" lines=10 line_length=100
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 100, lines: 10, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 44, raw: "GIVEN generate_content name=\"content\" lines=10 line_length=100"}, 44)
    # line 45: WHEN truncate_tail content_var="content" max_bytes=200
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_tail, %{content_var: "content", max_bytes: 200}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 45, raw: "WHEN truncate_tail content_var=\"content\" max_bytes=200"}, 45)
    # line 46: THEN assert_truncation_result truncated=true truncated_by="bytes"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: true, truncated_by: "bytes"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 46, raw: "THEN assert_truncation_result truncated=true truncated_by=\"bytes\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-009
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-009] tail 超行数限制截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-009"}
    # line 49: GIVEN generate_content name="content" lines=100 line_length=10
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 10, lines: 100, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 49, raw: "GIVEN generate_content name=\"content\" lines=100 line_length=10"}, 49)
    # line 50: WHEN truncate_tail content_var="content" max_lines=5 max_bytes=100000
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_tail, %{content_var: "content", max_bytes: 100000, max_lines: 5}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 50, raw: "WHEN truncate_tail content_var=\"content\" max_lines=5 max_bytes=100000"}, 50)
    # line 51: THEN assert_truncation_result truncated=true truncated_by="lines" output_lines=5
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{output_lines: 5, truncated: true, truncated_by: "lines"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 51, raw: "THEN assert_truncation_result truncated=true truncated_by=\"lines\" output_lines=5"}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-010
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-010]" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-010"}
    # line 54: GIVEN set_var name="content" value="你好世界测试\n第二行中文\n第三行数据\n第四行内容\n第五行结束"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: "你好世界测试\\n第二行中文\\n第三行数据\\n第四行内容\\n第五行结束"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 54, raw: "GIVEN set_var name=\"content\" value=\"你好世界测试\\n第二行中文\\n第三行数据\\n第四行内容\\n第五行结束\""}, 54)
    # line 55: WHEN truncate_tail content_var="content" max_bytes=40
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_tail, %{content_var: "content", max_bytes: 40}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 55, raw: "WHEN truncate_tail content_var=\"content\" max_bytes=40"}, 55)
    # line 56: THEN assert_truncation_result truncated=true truncated_by="bytes" last_line_partial=true valid_utf8=true
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{last_line_partial: true, truncated: true, truncated_by: "bytes", valid_utf8: true}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 56, raw: "THEN assert_truncation_result truncated=true truncated_by=\"bytes\" last_line_partial=true valid_utf8=true"}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-011
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-011] line 短行不截断" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-011"}
    # line 61: GIVEN set_var name="content" value="short line"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :set_var, %{name: "content", value: "short line"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 61, raw: "GIVEN set_var name=\"content\" value=\"short line\""}, 61)
    # line 62: WHEN truncate_line content_var="content" max_chars=500
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_line, %{content_var: "content", max_chars: 500}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 62, raw: "WHEN truncate_line content_var=\"content\" max_chars=500"}, 62)
    # line 63: THEN assert_truncation_result truncated=false
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{truncated: false}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 63, raw: "THEN assert_truncation_result truncated=false"}, 63)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-012
  @tag :test_runtime
  @tag :unit
  test "[BDD-TRC-012] line 长行截断含 marker" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-012"}
    # line 66: GIVEN generate_content name="content" lines=1 line_length=1000
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :generate_content, %{line_length: 1000, lines: 1, name: "content"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 66, raw: "GIVEN generate_content name=\"content\" lines=1 line_length=1000"}, 66)
    # line 67: WHEN truncate_line content_var="content" max_chars=50
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :truncate_line, %{content_var: "content", max_chars: 50}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 67, raw: "WHEN truncate_line content_var=\"content\" max_chars=50"}, 67)
    # line 68: THEN assert_truncation_result truncated=true truncated_by="chars" content_contains="... [truncated]"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_result, %{content_contains: "... [truncated]", truncated: true, truncated_by: "chars"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 68, raw: "THEN assert_truncation_result truncated=true truncated_by=\"chars\" content_contains=\"... [truncated]\""}, 68)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-013
  @tag :external_io
  @tag :unit
  test "[BDD-TRC-013] read 工具截断含续读提示" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-013"}
    # line 73: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 73, raw: "GIVEN create_temp_dir"}, 73)
    # line 74: GIVEN create_large_file path="big.txt" lines=500 line_length=200
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_large_file, %{line_length: 200, lines: 500, path: "big.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 74, raw: "GIVEN create_large_file path=\"big.txt\" lines=500 line_length=200"}, 74)
    # line 75: WHEN tool_read path="big.txt"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_read, %{path: "big.txt"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 75, raw: "WHEN tool_read path=\"big.txt\""}, 75)
    # line 76: THEN assert_truncation_notification contains="offset="
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_notification, %{contains: "offset="}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 76, raw: "THEN assert_truncation_notification contains=\"offset=\""}, 76)
    _ctx = ctx
    :ok
  end

  # Source: BDD-TRC-014
  @tag :external_io
  @tag :unit
  test "[BDD-TRC-014] bash 工具截断含原始大小" do
    run_id = Gong.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-TRC-014"}
    # line 79: GIVEN create_temp_dir
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :given, :create_temp_dir, %{}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 79, raw: "GIVEN create_temp_dir"}, 79)
    # line 80: WHEN tool_bash command="seq 1 20000"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :when, :tool_bash, %{command: "seq 1 20000"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 80, raw: "WHEN tool_bash command=\"seq 1 20000\""}, 80)
    # line 81: THEN assert_truncation_notification contains="字节"
    ctx = Gong.BDD.Instructions.V1.run_step!(ctx, :then, :assert_truncation_notification, %{contains: "字节"}, %{file: "/home/wangbo/document/gong/docs/bdd/truncate_system.dsl", line: 81, raw: "THEN assert_truncation_notification contains=\"字节\""}, 81)
    _ctx = ctx
    :ok
  end

end
